[short="Life and Experiences of Jane Pearson"]
== Selection from The Life and Experiences of Jane Pearson

It has long remained with weight upon my mind to
leave a few remarks respecting the Lord`'s dealings,
when He was pleased to lay His hand upon me in judgment for my backslidings;
hoping it may be of service to some poor, tossed, afflicted, tempted, bewildered mind.
For I do believe it would have been of service to me in
my painful moments to have beheld the footsteps of others,
if I had had the stability to read, or the quietness of mind to be instructed;
which for a time I did not, being feeble and sorely broken,
bemoaning myself by reason of the disquietude of my heart.

I was born at Newtown, near Carlisle, of sober, religious parents.
My father dying when I was young,
I had more experience of my mother`'s religious care in our instruction.
She was left with four of us to bring up;
and her zeal and care for her offspring abated not,
so that I have a good account to give of her pious care and concern for us.
On that account, she hired a schoolmaster in the house, to teach her children,
and to prevent our being corrupted or learning the
improper customs of the people amongst whom we dwelt;
so that we were kept, more than many others of our age,
from associating with those of other persuasions.

It pleased the Lord by His good Spirit to work in my heart in my young years,
which brought a godly sorrow over me,
and a fear lest I should be taken away in my childish follies.
When the funeral bell used to toll for those of other religious persuasions,
oh the awe and inward fear that attended me on those occasions!
I would say in my heart;
"`These have now been called off the stage of this world, and fixed as forever they must remain!`"
My uneasiness at times so far prevailed,
that I was desirous of knowing the age of the deceased,
and whether they were of ages similar to myself; and if they were, it added to my fears,
which at that time were piercing.
But if they were further advanced in life,
I endeavored to appease my fears by considering myself young,
and that I might escape such a removal in my youth; for I was afraid to die,
and that awful^
footnote:[Throughout this journal,
the world _awful_ carries its original meaning of "`full of awe,`"
or "`worthy of respect or fear.`"]
"`forever and ever,`" brought sadness over me.

I loved to read the Scriptures, especially the New Testament;
and when I read the passage where our blessed Lord is described
as having suffered so much from the proud professors^
footnote:[In this journal,
the word _professor_ refers to anyone who professes faith in Christ.
Here the word has nothing to do with teachers or scholars.]
of religion, who despitefully treated Him and crucified Him, it afflicted me deeply.
I believed I would not have done such a thing,
and so my heart became melted and tendered under a sense of it.

About this time it pleased the Lord to send into our parts Mary Kirby,
a minister of Norfolk; and she being alone, requested me to accompany her.
My mother gave me up, and it was a time of reaping some advantage;
for when I returned home,
I felt my heart in a good measure cleansed and emptied of its old inhabitants.
My stiff will having been measurably subdued, and having learned to love retirement,
I was drawn from my old companions.

I then witnessed a state of deep poverty of spirit,
which caused me to address the Almighty in this way: "`Lord,
what would You have me to do?`"
At that time I did not know there was anything in my conduct which displeased Him;
but His Word in me was, "`I must not only cease to do evil,
but I must learn to do well.`"^
footnote:[See Isaiah 1:16-17]
Thus I experienced, when the unclean spirit has gone out, we too walk through dry places,
seeking rest but finding none.
Oh, that this time of drought and emptiness was but patiently abode in!
But when all the old inhabitants are cast out,
the creaturely part is apt to reach for something
in order to make up the loss it has sustained;
for how hard is it to live without pursuing life in created things or externals!
The senses are continually seeking for something to heal this deadly wound,
and to replace something in an emptied mind; for it is hard thus to die to self.
Therefore many are apt to connect themselves again with those who are worse than themselves,
and their last state is worse than the first.

I feel such heavenly serenity in my endeavors to bring together these few remarks,
which have long lain among my papers,
so that I have no doubt it is right for me to leave them to posterity;
having a living hope in my heart that the perusal of these faithful sayings will,
under the guidance of Providence,
tend to reach and reduce the uncircumcised Philistine nature in some.

The infirmities attending my family in my younger years kept me much at home;
and now my own weakness and infirmities are great and many.
Nevertheless my love is true to the great and good cause,
and I should be willing to go the world over to edify the body,
and promote the reformation of mankind,
and the redemption of their souls through Jesus Christ.

I continued for a time to have a deep sense of privation and emptiness.
I was sitting in our women`'s meeting for discipline at Carlisle,
when it appeared clear to me, that if I continued to walk inwardly with God,
I should soon have to speak to others.
The suggestion that I was to be drawn by Him to minister
to others was so far from humbling me,
that I did not even ask to be excused, or pray my Divine Master to have patience with me;
but I resolutely said; "`I will never do so.`"
So I set myself aside like a broken bow,
and I believe I went into greater alienation from
the Divine life than I had ever done before;
and truly, it would have been just if Infinite Wisdom had cut me off in my disobedience.
I was guilty of many wrong things, which brought heavy judgment upon me.
At this time I was living with an aunt at Carlisle, and was much exposed to the world;
for she kept a shop, and I was out from under the strict eye of my mother.

I was now in about the seventeenth or eighteenth year of my age.
Through every dispensation, I had felt a great love for good Friends,
and they often manifested a love for me, recognizing the valuable part in me,
and overlooking that which was rebukable,
trusting (I doubt not) that the Lord would carry on His own work.
And their open carriage towards me, was so far from begetting disesteem in me,
or inducing me to account them undiscerning,
that it had an effect upon the better part in me;
for indeed I could have washed the saints`' feet.
Ministering Friends lodged at my mother`'s house, and I sometimes got the blessing,
which is still fresh with me to this day.

At the age of between twenty-one and twenty-two, I was married to John Pearson, a sober,
religious young man.
About a year after my marriage, my false rest was broken; though I was rightly married,
and I trust in the Lord`'s wisdom.
United to a choice husband, I swam as in an ocean of pleasure;
but instead of peace on earth, I witnessed a heart-piercing sword.
My distraught condition was present with me day and night, whenever awake.
Indeed I slept but little.
Sleep departed from my eyes and slumber from my eyelids; so that when night came,
I wished for morning.
And though I had been preserved from gross evils,
so heavy was the Lord`'s hand in judgment against the sinful, impure part in me,
that there was sufficient work for His heart-piercing sword
which divides between the precious and the vile,
between that which serves Him, and that which serves Him not.

In my own view, my case was now exceedingly deplorable;
so that I neither ate nor slept much, which occasioned a visible decline in my health.
Indeed I was a wonder to behold; people wondering what had befallen me.
The enemy followed me closely with the most grievous besetments;
things that my very soul loathed he would charge upon me to be my own.
And I, not having strength to resist him with a
"`Get behind me, Satan,`" or on the other hand,
not having experience to distinguish between what
proceeded from the enemy and his grievous insinuations,
and what arose from the weakness of nature,
everything in me appeared out of order and as a confused mass.
I truly believed that none was ever in such a state before,
nor had I ever read of any Friends who I thought had gone through similar trying dispensations,
what if I say, _for fourteen years,_
during which I feared I should never get to the other side.

I ate my bread weeping, and mingled my drink with my tears.
I was as if among fiery serpents,
and in the jaws of a devouring adversary who was exulting over me,
insinuating that the next temptation would sweep me away,
and darting things into my mind one after another,
as swift as thought and as dark as the darkest night.
Oh, that my troubles were written with an iron pen and lead in the rock forever,^
footnote:[Job 19:24]
for surely they are far beyond my power of description;
and had not mercy been extended to me in this trying season, truly I had fallen.
The dispensation was so severe, that I could not see how to live under it,
and I wished the Almighty would, by an act of His power, snatch me from among mortals,
though it might be by an accidental death; for I still believed that if He did take me,
it would be in mercy.
So earnest was I after holiness and virtue,
that I often besought Him that He would never permit me to sin against Him,
that I might not be eternally ranked with unclean and abominable spirits,
which my very soul loathed.

I now abhorred myself as in dust and ashes,
because the enemy was thus permitted to assault me.
But through all, my intellect was preserved clear, and my reason sound.

During this time I was much drawn inward in prayer; for truly my tempted,
bewildered state called for it; and for a time, I believe I prayed without ceasing.
And yet the Lord knew what I needed, in order to fit me for His work and service.
And so, for my further refinement, He permitted the enemy to come still nearer;
although I might have said with one formerly, "`Why does He yet find fault,
for who has resisted His will?`"^
footnote:[Romans 9:19]

The following is one of the most agonizing trials I ever met with.
One evening, when the enemy accused me of evil,
and I turned in prayer to the Judge of all the earth,
making my appeal that He knew I was not wicked,
and beseeching that He would rebuke the devourer for my sake,
and set me at liberty to serve Him--it was darted as quick as lightning into my mind,
"`There is no God!`"
Oh, then how did I mourn,
believing there had never been a man or woman with the least
remnant of good that was ever tried in this manner.
I thought I was now sinning against the Holy Spirit,
and that I was the most wretched creature upon earth.
And the enemy followed hard with his bitter whispering, saying,
"`To what do you pray? There is no God.`"

I never opened my condition under this painful dispensation to anyone;
for I believed that whoever I exposed my mind to,
would suppose I had been guilty of some horrendous thing, and was therefore a castaway.
And I thought that if I met with discouragement from them,
I would not be able to bear the Lord`'s hand in judgment,
because I had sinned against Him.
But at length I witnessed the truth of that declaration:
"`When Your judgments are in the earth,
the inhabitants of the world will learn righteousness;`"^
footnote:[Isaiah 26:9]
for truly I did come to experience inward purity of heart and cleanness of hands.
And in the Lord`'s own time He gave access to His throne,
and the Spirit of prayer and supplication was poured out upon me,
along with a "`Verily there is a God that judges in the earth.`"^
footnote:[Psalms 58:11]
I then felt a holy sense of this truth, "`The Lord lives,`" and
"`because He lives, I live also.`"^
footnote:[John 14:19]

When this dispensation had prepared the way of the Lord and made His paths straight,
then it passed away, and I could say, "`The Lord lives, and I speak not falsely,
because I know what the precious knowledge of God has cost me.`"
I note these things for the help of any that may be tried as I have been;
for if I had met with any similar account it would have relieved me.
There may be testimonies of Friends in the account
of their lives that are somewhat similar,
but I had not read them, or if I had, they had gone from my mind.
Nor could I believe that any who were under Divine notice,
or the discipline of the holy Hand,
were permitted to abide so long a time under such dark bewildering suggestions.

May all who are similarly proved, believe that a way will be made for their escape!
Do not lose heart nor cast away your confidence!
I feel united to the suffering seed wherever they are, or of whatever society they may be.
I mourn with those that mourn, feeling compassion for their distress.
My commiseration and tender feeling is towards these,
and I can address them--not from any degree of experience to boast of,
but from the depth of humility I can say--
"`Trust in God. He can set His seed at liberty, and will do it.`"

I now began to have great scruples respecting my wearing of apparel,
and also that of my children, and the furniture of our house,
and I longed to have all things in plainness and simplicity.
I thought of John`'s raiment of camel`'s hair, with a leather girdle about his loins,
and that his food was locusts and wild honey.
There was no delicacy here, either in eating or apparel.
Whatever the strong will in me seemed to loath, or have an aversion to,
into that very thing, in the cross, I was led;
though it seemed an indignity to my very frame and disposition,
which was not thoroughly redeemed from nicety and
a desire to be something in the eyes of the world.
I was led in this way until my will was subdued, and I was simple enough,
through being mortified every moment;
for I had always some scruple upon my mind whether things were right or not,
until I was rendered flexible and docile,
ready to take any impression the Lord would stamp upon me.
And oh how I pray it may be a stamp of holiness, during my stay in mutability;
and afterwards that I may join the triumphant church,
praising the Lord God and the Lamb forever and ever.

About this time, I began to experience some light and life about me.
I could not have believed that I would be so clear of the
bitter whisperings and insinuations of the crooked,
piercing serpent: for it is natural to conclude, when things are so out of order,
and the adversary has effected such an inroad into the mind, making a prey of it,
that things will be hard to set right.
But it is the Lord`'s work, and He shall have the praise; for all is due to Him,
and nothing is due to the creature.

I measurably witnessed an overcoming, and a little of getting the victory;
for I felt the head of the serpent was bruised, the accuser cast down,
his accusations silenced, and myself acquitted of his false high charges against me.
And in the place of all this,
I obtained a precious feeling of justification--where
old things were done away by that baptism which saves,
and all things had become new, and all things were of God.
I now began again to have some view that I must tell
to others what the Lord had done for my soul,
how He had plucked me out of the horrible pit, out of the mire and clay,
letting me feel the sure foundation.
I saw that I was to keep upon that bottom,
and to proclaim the new song that He would put into my mouth.

This was a day of close trial, for I was brought to the test,
whether I would keep my covenant that I had made with the
Lord in the days of my deep distress--which was,
that if He would but set me clear of the enemy, then command what He pleased,
I would obey, let it be what it would.
In assembling with the Lord`'s people (and it was a favor
to me that I was amongst a spiritually living people),
our meetings were often favored with living testimonies.
On such occasions,
Scripture sentences would at times impress my mind with some degree of life and power,
and according to my infant state and inexperience,
I felt some concern to declare them to the audience,
though the evidence was not as full and clear as
my diffident mind requested and really needed;
for I was desirous that I might be preserved from saying
"`'`Thus says the Lord God,`' when the Lord had not spoken.`"^
footnote:[Ezekiel 13:17; 22:28]

This caused a strong conflict, a trying of the fleece both wet and dry,
for my natural timidity closely adhered to a corresponding
care not to offer untimely fruit which soon comes to decay.
This made me very wary and cautious,
as I believed many had mistaken the preparation for
this office to be the commission itself,
and so had been dwarfs in the ministry.
On the other hand,
the remembrance of the covenant I had made with the
Lord in the days of my sore bondage and deep captivity,
and my now not answering His requirings, made this a time of great distress for me.
In meetings, matter would arise and spread in my mind towards the people,
and yet I did not feel the command to speak.
Oh, if any should be similarly tried,
if they are resigned and have minds devoted to the Lord, to such I would say, "`Fear not;
the time will come when you will not doubt respecting the Lord`'s will.`"

I was about nine months under this trying dispensation.
It wore down my bodily strength; my knees were weak, my flesh failed,
though not from refraining from food.
My face was often sorrowful through much weeping in these winnowing, sifting seasons,
and on my eye-lids sat the shadow of death.
Yet through all, I had a little hope, which as an anchor stayed my soul.
And a holy belief was raised that He who was my confidence,
would in His own time unfold the mysteries of His kingdom and give an undoubted evidence,
with unsullied clearness,
that it was His will for the candle He had lit be set on the candlestick,
and to give light to those around.

Thanks be to His ever-worthy name, He fulfilled it.
For when the right time came, in which I was to open my mouth in a public meeting,
I had no doubt of its being His mind and will.
Yet even so, through fear, I reasoned it away, but was not severely chastened for it,
as my heart was steadily bent to serve Him.
The will to do good was present, but in the performance of it I felt weak;
so the Lord forgave me, and my mind enjoyed good until the next meeting day.
I then went in great fear to our little meeting at Graysouthen.
A few words presented livingly to my mind, which I uttered in much fear.
And I well remember the subject; the essence of which was,
that if we were but more inwardly turned to the Lord in our meetings,
they would be more favored than we often found them to be.
And is not this a truth at the present day?

My being thus cautiously led in the beginning,
has been helpful to me through the remaining part of my life as it pertains to the ministry,
in my watching against false views and presentations to my mind,
or mistaking the imaginary part for the revealed will of God.
Oh, the peace that I felt that night after that short testimony!
It would have been acceptable then to have "`departed and to have been with Christ,
which is far better.`"^
footnote:[Philippians 1:23]

I had now great peace of mind, so that instead of my heart being a place for dragons,
for owls, and for screech owls, for cormorants, and for bitterns,
there began to be a melody in it, as it were, the voice of the Son of God,
whose countenance is lovely.
And now the myrtle, the box tree,
and the pine tree sprang up in that heart which before
had been a breeding place for nettles.
This is the change that is wrought in man by being born
again of the incorruptible Seed and Word of God.
This was the change that was wrought in me.

I was then frequently engaged to speak in meetings, and had satisfaction in so doing,
and Friends did not discourage me in my little childlike movings,
but rather approved them, though with a godly care.
And through the Lord`'s abundant mercy, I moved in my gift in simplicity,
and did not choose for myself what to speak, nor did I seek after openings,
nor dress my communications according to the creaturely will,
neither dared I to restrain my openings--all of which are unsavory.
The Lord taught me to let it go just as it came.

As I had a great love and care for the Lord`'s blessed cause,
that it might not suffer through weak advocates espousing it,
so I always thought lowly of myself.
Sometimes, by keeping back some of what I was given to offer,
I became the author of confusion and disorder, and thus the people were not so edified,
nor I so comforted, as might have been expected from the conflict I had undergone.
I believe this error had some foundation in my wanting
to have "`a pattern of sound words`"^
footnote:[2 Timothy 1:13]
that none could condemn.
For though I did not seek divine openings, or dress them according as I pleased,
yet all must have a mode of expressing themselves that is suitable to the matter,
in order to convey to the audience their sentiments on religious things.
On this ground,
I sometimes wished to have my little offering nicely
set in order in my mind before speaking,
for I feared being guilty of misquoting or misapplying the holy Scriptures.
But I was led clearly to see that the ministers of Christ
must rise when perhaps only a word is given them,
and must minister according to the ability with which they are favored,
not at all fearing man, whose breath is in his nostrils,
but serving and fearing the Lord only.

I now began to have great outward trials, when there was an abatement of the inward.
I had an affectionate husband, who in my spiritual infancy bore part of my sufferings.
I had seven fine children, four girls and the youngest three boys.
Till this time the Lord had made a hedge around us and all that we had.
Though we had not much to begin with in the world, we increased fast in temporal things.
It pleased the Lord to remove two of my youngest children by the small-pox.
I grieved much that a breach had been made upon us; indeed I fretted too much.
There was then a language proclaimed to my inward ear,
that if I did not cease inordinate grieving, I should have more troubles.
The affectionate part was strong,
yet I trust I did not murmur against these dispensations of unerring Wisdom.

In the next year my beloved husband was taken from me!
Oh, I could then have parted with all my children to have had him spared;
for in him I was so bound up that I believed if he died, I could not live.
He was my outward strength, and on him I relied for everything in this world.
I am inclined to give forth a testimony to his worth,
as the widow`'s mite to her children, or children`'s children,
that when we are gone they may see from what kind of stock they have sprung.
For the welfare of these my very soul is moved within me,
and causes me to go about bowed down,
imploring that Divine assistance may be their aid through this valley of tears.

[.embedded-content-document.testimony]
--

[.blurb]
=== Jane Pearson`'s Testimony concerning her dear deceased husband, John Pearson, who departed this life the 14th of sixth month, 1774.

He was born of believing parents who gave him an acceptable education, and I believe,
according to the best of their ability, trained him up in the nurture of the Lord.
He was religiously inclined from his youth,
so that in some sense he was a Nazarite from his birth,
giving full proof that he sought a heavenly country.
For in this world he had various struggles, being more exposed to it than many others,
as his business was a linen manufacturer.
Yet he conducted himself with honor through all his engagements,
and gained a handsome subsistence for his family; and I may say without doubt,
that he retained his spiritual life through all.

He was a man of an innocent life and conduct, of a meek disposition,
readier to take harsh treatment than to give it,
and would suffer wrong rather than resent an injury.
He was temperate even to abstinence.
In the relation of a husband, he was unexceptionable.
When I consider his tenderness towards me and his family, I can scarcely but lament;
yet I believe he is removed to the haven of rest,
for I thought it was apparent that the grave would have no victory at his dissolution.
His illness was tedious, but he was quite resigned,
whether life or death should be his portion.
And he frequently said that he longed to be gone,
and that he scarcely thought it would be possible for him to be so willing to leave us.

A Friend coming in the day before he died had an opportunity with him,
which was an acceptable time.
The Friend expressed to him that he might still get a little better.
He answered, "`I had rather go; I have felt the pains of death; oh let me go!`"
It appeared that he was quite reconciled to the grave, and I said, "`O then, my dear,
you must be satisfied your change will be well?`"
He answered, "`Yes, I believe so;`" speaking with becoming humility.
The day before he died,
he felt his pulse steadily three times in order to know how near his change was,
and he inquired of the doctor how long he might continue?
I desired he might not ask that question, and he, lamb-like, did not repeat it.

I am satisfied he felt an assurance of acceptance with the Almighty,
which was manifest by the heavenly strength and serenity
that accompanied him to his last moments.
His mother, who was an aged person, and under great infirmities,
being brought in to take her leave of him,
he in a prophetic manner told her that he should go first,
but that she would soon follow after.
And accordingly it happened, for as he expired,
she began to show symptoms of her dissolution,
and continued but about two hours after him;
so they finished their course nearly together.

Oh, my loss is inexpressible!
His kindness, his nearness to me in a religious sense, cannot be set forth.
I had gone through various and deep provings;
many weary years had passed over my head while I was under the preparing hand of my God.
But his compassion, his patience towards me,
his condescension to my weakness in my infant state, cannot be penned.
His memory is blessed,
and his excellent virtues ascend to the Father of
spirits and resemble the prayers and alms of Cornelius,
held in everlasting remembrance.

I have endeavored not to be swayed by affection in giving this summary account,
but have just related what I think the spirit in me bears witness to the truth of;
nor did I feel easy without doing it.
He departed without any struggle, as one falling into the sweetest of slumbers,
and was decently buried in Friends`' burying-ground, at Graysouthen,
aged forty-nine years.

[.signed-section-signature]
Jane Pearson.

--

The Lord was now about to divest me of my beloveds.
The next year He took my eldest son in a fever, so I was left with no son.
He also made it manifest to me that He required of
me to travel a little in the service of Truth.
I gave up, and my friends favored me with a certificate.^
footnote:[Ministers in the Society of Friends always traveled with a written certificate
of endorsement and unity prepared by elders of the meeting to which they belonged.]
I set off on my journey, with my much honored friend Hannah Harris.
I accompanied her through Lancashire,
and then my dear friend Barbara Drewry met me at Settle.
We visited all of Yorkshire, except for Richmond Monthly Meeting.
Then, feeling a strong draft home, I returned and found my family well,
except for my dear mother who resided with me.
She was a little on the decline, yet not so as to be much noticed.
But in about two or three weeks she fell sick and died.
I mention this that Friends may attend to their feelings
and drawings concerning when to return home,
for had she departed in my absence,
I would have been in danger of letting in the reasoner.
Oh, the kindness of God who prolonged her life till my return.

I was now left with my father-in-law, who was a valuable man, and my four daughters.
The second youngest, an amiable young woman of about nineteen,
after going a little abroad, lost her health.
She continued in a state of great weakness for about three years,
and departed this life in 1784, my father-in-law dying a little before her.

I was now left with three daughters.
The family sits solitary that was once full of people;
but the Lord has been exceedingly kind to me.
When I mourned for the loss of my connections, my husband especially,
condescending Kindness graciously pleaded with me in this way: "`What have I done to you?
I have taken your beloveds to a mansion of rest, called them to a better life.
And I will remove, as it pleases Me, the remainder of your family;
and then you will meet, never more to part.`"
At that moment I had a hope, yes a precious faith,
that the Lord would mercifully preserve me and mine till the end in a degree of innocence.

I must acknowledge,
I had allowed a strong persuasion to prevail in my mind
that the Lord had removed my husband from me in displeasure,
because I had not faithfully discharged myself in the ministry,
or because something else was wrong with me.
I was even so weak as to require from Him a sign,
although He had before fully satisfied me it was
not because of displeasure towards either of us.
But oh, it was with me a time of great dejection.
What I asked at that time was, that He would cause some of His servants,
with whom I had never corresponded, to write to me, and I would take it as a sign.
He had chastened in His mercy, and now allowed Himself to be entreated;
for that valuable Friend, Mabel Wigham, addressed a letter to me in tender sympathy,
communicated her feelings that my husband was removed in mercy,
and that I and my children would be preserved.
I note this, that Friends may be faithful in all respects, for it did me much good.

I now had a concern on my mind (and I think it had been before me for some years)
to visit the meetings of Friends in the western part of this nation.
Cornwall pressed upon me very closely, so that if I had wings,
I could have flown to it for rest.
I informed some of my friends, who encouraged me and united with me in my prospect.
I then acquainted the Monthly Meeting and obtained its certificate,
and I had my dear friend, M. Haworth, of Haslingden, for a companion.
We visited most meetings in Lancashire, Cheshire, Shropshire, Worcestershire,
Somersetshire, Devonshire, and Cornwall.
The Lord wrought mightily in me towards the distressed,
for I had passed through much affliction, and was thereby rendered very sensitive,
readily catching a sense of sorrow wherever I found it.
I missed several meetings on my way home, being poorly in health,
and believing it safe and lawful for me to return.
I found my family well, and had the evidence of peace answering my obedience.

I have now arrived at the fifty-sixth year of my age, and still afflictions accompany me.
My second daughter being removed by death, I have but two remaining.
She was an innocent, virtuous young woman,
bore a lingering illness with patience and resignation,
and I believe is gathered to her rest in mercy.

In 1791 I moved to Whitehaven to reside, before the death of my youngest daughter;
to whose marriage with a Friend belonging to that meeting I had consented.
Our moving there was also very much the mind of both my daughters.
The daughter who still resided with me was desirous of living
there in order to be helpful to her married sister,
whose family was increasing.
But oh the close exercise I have had in this meeting!
Truly it has worn me down,
along with other trying circumstances which befell me at that place.
Indeed, many a bitter cup have I and my poor children had to drink there.
But if it has contributed to our refinement, then it is well;
for surely our bodies were enfeebled thereby.
I did my best under the heavy trials I met with.
The Lord knows my prayers were almost incessant while
under the weight of unpleasant things.

My youngest daughter was a religious, pious young woman, and died the year that we moved.
She was exceedingly delicate, of a meek disposition, and tender-spirited;
and yet she had waded through difficulties,
so that in her dying moments she expressed that streams of tears had run down her cheeks,
and that if she died then (which she was not afraid to do), she died innocent;
for she had never done wrong to anyone.
And she often said encouragingly, "`The Lord knows what is best for us.`"
She had a strong apprehension that she should die,
but from a sweet prospect of good that I had had respecting
her while in a meeting a little before this time,
I believed all would be well.
From this discovery, I took hold of a hope that she might recover,
to which she remarked during her illness: "`Mother,`" said she,
"`you have been mistaken.`"
I answered: "`My dear, I saw something very comfortable about you,
and I believed all would be well.`"
She answered, "`All _will_ be well,`" and then added,
"`I have often thought of that Friend from Manchester,
who pointed out to us during a family meeting that some present had not long to stay.
But the state he spoke to seemed too good for me to accept as my own.
I applied it to another in the company, who at that time was indisposed.`"
My daughter left three fine children under the charge of surviving relations.

Though it is my lot often to sit silent at meetings in the place where I now reside,
yet I have precious openings and divine intimations on my return home from them,
even respecting individuals.
But hardness of heart has crept into the minds of some,
and it may be right to let them alone.

2nd of sixth month, 1793.--I know not for what I am held at this place,
except it be to faithfully suffer with the suffering seed here.
I have renewedly felt a precious union with our dear Lord in His
crucified state in the hearts of professors of Christianity.
Oh, the plungings I have witnessed in our meetings!
There is an active spirit that has got in, that takes its food upon the surface,
or catches at it flying in the airy regions.
With food of this nature, some seek to feed and to be fed.
I have sat painfully under some recent testimonies when
it seemed clear to me that sin still held its empire,
and that what was delivered, though sound truths, yet did not slay the man of sin.
But I am alluding to none belonging to our meeting;
there is a precious seed in this place with which, in a great measure, I can unite.

1st of fifth month, 1794.--I have been at meeting this day, which was heavy.
I felt clouds gathering thickly, the sun and moon darkened,
the greater and lesser lights withdrawn.
In my deeply trying, inward labor, I saw no light in the horizon,
and very confidently believed the bitterness of death was around.
I struggled in silence till my gracious Master gave me to see that where He was,
there His servant should be also.
I derived some consolation from this,
reposing in a belief that I was of the suffering seed,
though the least member in the body, or the lowest in the Father`'s house.
I think I have had in this meeting such a diversity of feelings,
and that perhaps I have experienced the two extremes of happiness and woe.
At one time in silence, there was a confirming language inwardly spoken;
and though a poor worm, I had hopes it might be applied to myself.
It was this: "`My presence shall go with you,
and I will give you rest,`" under which I was ready to sing the song of Moses,
the servant of the Lord, and the song of the Lamb.
At another time,
my mind was so overshadowed with the power of Truth that
the season was too solemn for any vocal voice to be heard,
the cloud and glory so great that none could minister.

Sixth month.--I have now returned from Broughton,
where I have been nine weeks on account of my only
surviving daughter`'s weak state of health.
I felt comfortable while there,
and great enlargement of heart towards the few Friends belonging to that place.
Oh, may they be profited!
Truly it was free mercy handed to them,
and not for works of righteousness that they have done,
for I think them deficient in that great duty of attending religious meetings.
How sorrowful it is, when elders and overseers stay at home by their baggage,^
footnote:[A reference to 1 Samuel 25:13 KJV]
while others are wading deeply for the promotion of Truth!

Whitehaven, eighth month,
1794.--This day our Monthly Meeting has been a very favored season to me.
My soul arose above all its troubles,
under a precious sense that in my sojourning thus far through life,
the Lord has always eyed me for good and has watched my goings.
And though I cannot say I never made false steps,
yet He who knows my heart knows the cause to be weakness.
Oh, how weak are we when divested of His saving help!
Yet He has in mercy fully forgiven all,
and graciously given me a foretaste of the joys of
His kingdom--a sense that has no feeling of sorrow,
no more sighing, no weeping, but a joy without mixture.
In this state I have been ready to think the days of my mourning are nearly ended,
having a strong "`desire to depart and to be with Christ,`"^
footnote:[Philippians 1:23]
and feeling all my soul`'s enemies subdued,
so that I could pray for them that have spitefully used me.
In this heavenly place in Christ Jesus, it is good for us to abide.
This day I was silent; the fulness of glory being too great to minister.

22nd, 1794.--Have been at meeting.
Oh, the sifting I experience in regard to the ministry I am gifted with!
Though I believe I was rightly called, that I entered at the right time,
and have moved with godly fear in it, not choosing my own way, nor carving for myself,
yet I am so low as to think I have never been of use.
I opened my mouth this day, as I thought, from a small impulse,
or the moving of prophetic instruction,
out of my little measure of flour to bake Him some bread first.^
footnote:[A reference to 1 Kings 17:12,
in the story of Elijah and the widow of Zarephath.]
Here there is no excess, but only a grain of faith that His supply will be afforded,
answering my need.
I ventured my offering in true simplicity, so far as I know.
But oh, the buffeting at my return home was truly bitter!

I have now arrived near the sixtieth year of my age,
and my bodily strength is much impaired.
I have grown very weak,
and I do not expect it will be long before the narrow
confines of the silent grave will enclose me.
Oh happy moment, when I shall be freed from the sight and voice of the oppressor.
For although some might be sensible that I have undergone hard things,
yet none have known the anguish of my heart.
It is beyond all description, but it is known to God.
I have often had to remember holy Job, and to quote him in the exercise of my gift,
in honest labor among the people, and to say, "`Even today is my complaint bitter,
my stroke is heavier than my groaning;`"^
footnote:[Job 23:2 KJV]
and so mine has been, even at this late period of my life.
He also declares, "`I cried out of wrong, but am not heard.
I cried aloud, but there is no judgment.`"^
footnote:[Job 19:7]

I attempted to conclude this day (as I have at some former
seasons) that I would preach no more in this place;
for the spring of the Gospel is much shut up.
I find that if I speak, my grief is not relieved, if I remain silent, how am I eased?^
footnote:[Job 16:6]
For I have tried from meeting to meeting what silence would do for me.
I search myself to find the cause why I am not lively
in my ministry as in the days of my youth.
Truly I conclude there is no life in me,
so that I now most earnestly wish for the lodging of a wayfaring man in the wilderness,
where I might go from my people and leave them.
I feel weary of these suffering seasons.
They are more than my frame can well bear.

Fourth month 8th, 1795.--I was at our weekday meeting,
in which I beheld that we are born to trouble, as the sparks fly upwards.^
footnote:[Job 5:7]
I saw that the human mind at seasons is like a sponge, drinking up affliction,
till it sinks in deep waters; yes, they flow into the soul.
Oh, the perplexities that we experience in this short space of time!
Few and evil have been our days, and we have not attained to the years of our forefathers.
In this state,
condescending Kindness mercifully led me to the Rock that is higher than I,
and my eyes saw that we fret over things unworthy of the notice of a redeemed mind,
and that if I, or my friends with whom I sat,
were but called upon to take leave of everything below the sun,
then all these perplexing anxieties would vanish away like an atom in the whirlwind,
and be of no weight at all.
We should then only lament that we had not looked above these momentary afflictions,
and fixed our confidence on the invisible Arm, the invincible power of Omnipotence.
But oh, how is the natural part attracted by visible objects!
While that which is born from above suffers through our not clinging to invisible things.

In this meeting I desired that I might be favored with an extraordinary visitation,
whereby I might be made willing to give up to any of the Lord`'s requirings,
having long had an exceedingly great dread upon my
spirit in regard to praying in public assemblies.
Oh, this broke the creaturely part in me, and laid me in the dust.
I could be willing to breathe mentally to the Lord during the whole of a meeting,
but when I should have fallen upon my knees to pray vocally, oh,
the reasonings I experienced!--that perhaps the cup of favor was not full enough;
that I had not come as near to His throne as I ought,
or was not sufficiently clothed with the garment of praise;
that a fervent desire for the good of my friends had not arrived at full height;
or that I had not enough of the indwelling of God`'s pure
Spirit to enable me to keep so close to His precious,
directing, all-saving power,
so as to be preserved from offering a word in prayer
of which He was not the author and requirer.

Although this is a pinching dispensation,
and I may now appear very much like a weakling who just entered into the service,
yet I have at various times before been prevailed
upon to call upon the name of the Lord in public.
But I have had to undergo great searching of heart afterward,
lest I should have made the smallest deviation or
sally from the precious life while so engaged;
so that now nature is ready to fail at the appearance and approach of intercession.
May the Lord help me!
Perhaps this little delineation, may be as "`face answering face in a glass,`"^
footnote:[Proverbs 27:19]
to some who are very conscientious in every movement, especially in vocal prayer;
and may it always be offered with a right understanding, seasoned with grace.

20th of eleventh month,
1796--I have felt a desire this morning to be thoroughly washed until I am made clean,
such as no launderer on earth could make white.^
footnote:[Mark 9:3]
Many are made willing to bear the various spiritual baptisms,
provided they are assured it is Jesus who is dipping them.
But so uncertain and seemingly casual are the occasions of their plungings,
that they do not believe He is the author of their immersion,
or that it is His holy hand that is washing and bathing them for their imperfections.
But if these baptisms are endured, then sin is mercifully done away;
and how can those that are dead to sin live any longer in it?

Third month 28th,
1797--I was favored once more to attend our Quarterly Meeting at Carlisle,
very near the place of my nativity and the meeting I belonged to for many years.
The meeting of ministers and elders was a favored season.
I had the evidence of peace in my little labors,
and indeed all the meetings were more or less endorsed
with the heart-solacing presence of Zion`'s King.
It felt like I was taking my leave, and I was helped to be faithful,
so that upon my return for many miles my cup ran over,
and I seemed anointed with the oil of gladness.
Great was my peace;
it was such a full foretaste of heavenly joy as I have not before experienced,
except when I first opened my mouth in testimony for the Lord.
There seemed nothing between my soul and its blessed Redeemer.
At that time my joy was so full that I longed to be dissolved,
feeling nothing but purity and holiness all about me.
Or at least, I had the sense of full acceptance with the Father in my endeavors to obey.

At Carlisle, I felt an engagement to supplicate God on behalf of the people.
I felt love for them, and some of the elders and ministers felt near to my inward life.
Indeed I had never before found more openness to plead with
them than in the select meeting for ministers and elders,
and I felt great peace in so doing.
In the time of supplication, which was at the close of the last meeting,
I thought I felt near access to the Almighty; for if I had not,
I would not have dared to call vocally upon His ever-blessed and worthy name.
During this awful and solemn time (for so it was to me), I supported myself on one knee,
my other having no strength in it,
which hindered my continuing in intercession as long
as might have tended to my solid comfort.
But the Almighty, who accepts the "`Abba Father,`" heard my little offering,
and I believe my effort was accepted.
And if I had only bent my knees and called upon His ever-worthy name,
He being the author of my supplication, in return for this humiliating dedication,
would have given the answer of peace.
Blessed be the name of the Lord forever.

Fourth month, 1800--I have been confined as of late through bodily indisposition,
during the forepart of which my sickness was extreme.
It appeared to me that I was making quick advances towards the grave,
although my first Divine impression was that I should not die at that time.
But as I knew a recent instance of a minister (with whom I had travelled),
whose death was entirely hidden from her, this made me sometimes rather unsure.

I had much bodily illness, but not much conflict of mind.
I was preserved still and quiet, which was not my nature, but surely God`'s mercy;
to His praise may it be inscribed upon my heart as long as I live.
I was favored with a fixed, steady, comfortable hope that if I then died,
it would be well with me.
I desire no more evidence when I shall really surrender my life;
for it seemed as if my dear Redeemer`'s arms enfolded me very safely,
in such a way that the wicked one (by whom I had
often been distressed on a sick bed) touched me not,
neither had any power over me.

First-day, 10th of fifth month,
1801--I was at meeting at Whitehaven and had a precious opening,
with which I was nearly ready to stand up.
But I am too much like the infirm man at the pool of Bethesda,
waiting for the moving of the waters, and while I am getting ready, another steps in.
It was so this day, and though but a few words were spoken by the individual,
and they not distinctly heard by me,
yet it left unspeakable anguish and sadness of spirit, so that the daughter of Judah,
for the remainder of the day, "`was trodden as in a wine press.`"^
footnote:[Lamentations 1:15]

Ninth month,
1801.--As in me there has been a remarkable instance
of God`'s mercy and power--His mercy in forgiving,
and power in upholding me--I can therefore do no less than praise Him here and eternally.
And whoever reads this, let them be humbled in the dust before Him;
for truly He is glorious in holiness, fearful in praises, doing wonders.

The latter part of this year, I have had a time of confinement through sickness,
and I have not been so favored in this season of weakness with that soul-sustaining
evidence of Divine regard as at some former times.
It may be that I had too much comforted myself in thinking upon the abundance
of favor that was mercifully granted to me in a previous illness,
not doubting, that if I was tried in a similar way, I might be equally supported;
and so I was in danger of being like Gideon, who, after his great achievement,
made an Ephod, and idolizing it, it became a snare unto him.

Sixth month 30th, 1802.--I was at our weekday meeting,
and was favored with a solemn silence,
resembling that in heaven where angels and archangels adore in profound silence.
Oh, I saw into the joys thereof, a place where sorrow cannot come,
and none of the inhabitants have any affliction.
I was this day favored to partake of Divine goodness in
the greatest degree that perhaps I have ever experienced.
The heavenly bread was handed to my soul in no sparing portion, with the language,
"`Take, eat, this is my body.`"^
footnote:[Matthew 26:26]

Towards the latter end of last year, 1801,
I had an apprehension that I must visit some of the southern or south-eastern counties.
It came, I thought, with considerable clearness.
I endeavored to keep as near to Good as possible, and I was rarely, when awake,
without some sense of this Divine requiring.
The latter end of the fifth month, 1802, seemed the right time for me to move in it.
I did not stagger at my own weak state (for I was really given up to go),
nor at the extreme weakness of my only surviving child;
so that it appeared like Abraham`'s trial in stretching
out his hand to offer his only son.

I wholly resigned my poor grandchildren, who indeed were orphans,
not daring to let the affectionate part hold sway.
I gave up my own life and theirs, and all that I had into the hands of the Almighty,
not daring to draw back one bit,
or even to wish that the service had not been required of me.
I dared no more dispute the voice than Abraham did
when he was called to go to the land of Moriah.
My nature perhaps recoiled, as his might do, without the hope that he had, "`My son,
the Lord will provide for Himself an offering.`"^
footnote:[Genesis 22:8]
Let the unbelievers step forward and question these and other sacred truths;
it matters not.
Their unbelief will perish with them, and cease to be propagated when they are no more.

But when the time arrived in which I was to prepare for the journey,
the prospect entirely closed, and I was fully released from it.
I bowed in humility and accepted my discharge,
feeling this caution--to keep my eye to the great Leader,
and not hastily reenter into my family affairs; but to be still and wait,
without rejoicing at my liberation.
Since this time I have continued to feel at liberty.

Fourth month 12th, 1803.--This morning before I rose,
I was pondering in my mind how many in our Society are rich and full,
as may be seen by their way of living and their clothing.
And that though their clothing is plain, yet it is costly,
and many are their suits of apparel.
I then recurred to my own low state, not regretting that it was so;
for I saw it is fitting for a redeemed people to be exemplary in eating, drinking,
and apparel.
During these considerations, my mind was satisfied by this language;
"`I will clothe you with salvation, and crown your end with peace.`"
Could I ask more for myself?
Surely no!
And being favored and broken under this, and feeling very near the throne of grace,
I was allowed (in humility) to petition for my daughter,
that she might have a place in the kingdom of heaven,
and accompany my spirit in the place seen fit for
me to inherit when I was unclothed of mortality.
After this, I prayed for my grandchildren.

Twelfth month 23rd, 1804.--First-day, I was at our meeting, in which I had an open time,
much to my own satisfaction, and I hope to that of others.
Indeed, Truth rose into dominion, and the opposite power sunk into insignificance.
Such instances have been rare with me.
In leaving the meeting, a sense of acceptance was given me,
measurably feeling the sentence of "`well done`" in my own particular,
along with a secret hope that if I continued to steer my course carefully,
keeping my eye to my guide,
and in simplicity and godly sincerity giving out
to the people what was immediately given,
pursuing the thread of my testimony in the power, and depending wholly upon the Lord,
He would be to me mouth and wisdom, tongue and utterance.
Thus Satan, for a while, became bruised under foot.

Fourth month 7th, 1805.--I have this day experienced deep baptism of soul.
Indeed, I thought it would hasten my dissolution.
Oh, merciful Lord, my times are in Your hand!
You know what I can bear.
Lighten my load, I pray You, or add to my strength,
for I am tried to the very life--"`crucified with Christ, nevertheless I live, yet not I,
but Christ lives in me.`"
Oh, grant me patience to bear these suffering seasons!
Surely You care that I serve alone.

In the latter end of 1805, or the beginning of 1806,
I had a sickness in which I was confined for some time.
And one night as I lay in bed, between the hours of nine and ten o`'clock,
being in a solid, weighty frame of spirit, breathing towards the Fountain of all good,
I beheld with my spiritual eye (as clearly as ever my outward
eye beheld any object) that the Ancient of Days descended.
His dread majesty enveloped me as in a cloud;
and being emboldened through His unmerited condescension,
I begged for a place in His glorious kingdom when unclothed of my mortal robes.
I write in awful fear.
I thought it was granted, and that I was allowed to proceed if I had anything further.
I then craved for my only daughter the same favor.
I thought that too was granted.
I then lifted up my eyes and heart, and mentally poured forth my soul, saying: "`Oh Lord,
the wickedness of man is great!`"--my mind being
expanded and bending in goodwill towards all.
And the answer I received was, "`My mercy is greater;`" and the vision closed.
But oh! the contented calm it left.

It is now nearly fifteen months since this display of God`'s mercy occurred,
and until this time I have not recorded it, lest any should think of me above what I am,
or that from such a discovery of unlimited mercy,
any sinner should presume to go on in their wickedness
in hopes that God would show them mercy at last.
But at this time, it has been again opened to me;
and after passing through many deep plungings,
I am stripped of all glorying except in the cross,
having no desire but that these lines may preach when I am no more,
and encourage some poor sinner to lift up his head in hope at what I have penned.

1806.--I am now grown old,
and it is announced that my declining years are not to be exempt from trials; indeed,
they truly increase.
My only daughter is afflicted with a cancer in her breast.
The pain and dreadfulness of the condition are such
that we languish without hope of her recovery.
Afflictive is this dispensation indeed,
having no solace but from a comfortable hope that her troubles
will end with the termination of her life.

Twelfth month 3rd, 1806.--In our weekday meeting,
I was engaged to set forth the necessity of not only receiving the seed of the kingdom,
but, with all readiness, allowing its growth;
for the work of Truth in the heart of man is described by
our Great Master to be progressive--"`first the blade,
then the ear, then the full corn in the ear.`"
I had peace in returning to my habitation, and this language presented to me:
"`Ever since you were born, My love has been to you.`"
This melted me.
May I be worthy of such a favor.

Third month 14th,
1807.--On taking a retrospect of the path assigned me through this valley of tears,
and the little records I have made thereof,
I have thought it may appear to others that I have been
more marred than my contemporaries in my deep early refinings;
or that since then, being unusually stripped of my beloved outward connections,
the tree has been wholly peeled.
But let none of Zion`'s travelers be discouraged at this.
For, to the praise of my heavenly Father and of the riches of His grace,
let it be remembered that sufficient strength for each day has been afforded me,
or else I never could have continued to this time.

My eldest and last daughter is now released from all her trials, and a gracious God,
who never fails in time of need, visited and upheld my mind in a marvelous manner.
At the time of her interment, while I sat in the meeting beside her coffin,
oh the unspeakable peace I felt,
with a consoling assurance that all her tears were forever wiped away!
Indeed they had flowed like rivers under deep religious exercise.
At that time,
the condescension of our heavenly Father was such to me (a poor unworthy creature) that
it seemed as if her pure spirit descended and rested upon her remains during the meeting.
Oh! how can I sufficiently adore Him!

Fifth month 4th, 1807.--Fourth-day, I was at meeting.
Some of our Friends have set off for London.
It was to me a solemn time, for I was much engaged in mental breathings;
the Spirit helping my weakness inwardly to pray.
A large portion of heavenly bread was handed to me without much wrestling,
and without having to set it before others.
And although our souls`' enemies may be numerous, a language livingly opened in me:
"`The Lord shall fight for you, and you shall hold your peace.`"^
footnote:[Exodus 14:14]
It applied to myself, as I had no commission from Him to divulge it to others.
Something like the earnest of the Spirit of adoption or holy promise accompanied my mind,
and closed with, "`Lord, You are good to us, we will praise You;
we will exalt Your name.`"
I had strong consolation in the only wise God--Omnipotent, Omniscient, and Omnipresent.
We are always in His sight, naked and bare before Him.
Oh, who would dare do evil!

Twelfth month 13th, 1807.--My family have all gone to meeting,
and through indisposition I am left at home.
But I must acknowledge the kindness of a gracious God to me,
who has been near in this time of confinement, allowing me to pour forth my soul,
and (at times, I have thought) even to lean on His very bosom.
And the comforting watchword is: "`Fear not, I am first and last.`"^
footnote:[Revelation 1:17]

First month 4th, 1808.--Rich favor was extended this morning to me, a poor worm,
and given in these consoling words: "`My love and care, yes, protecting care,
have ever been towards you, and I never will leave you nor forsake you.
Although Satan has, in days past, been permitted to roar and shoot his malignant arrows,
he shall now be still.`"

I craved the renewal of the Divine vision I had been favored with in a former illness,
but Infinite Wisdom saw fit to withhold anything further of that nature.
I adore and bless His holy name.
Oh!
I pray God, with my whole heart, that it may be thus with me in my last moments;
and I humbly trust it will, if I keep my place to the end;
for truly He has been a merciful God to me.
May the members of this meeting more and more seek after that power
which has so eminently interposed for the deliverance of my soul!
May not one of them be lost!
For truly great pains have been taken with this part of the Lord`'s vineyard.

Second month 7th, 1808.--For many months,
my mind has been preserved in a state of tranquillity,
despite the things in the outward that were at times afflicting.
I felt no evil inclination in myself, nor any temptation thereto;
and a merciful Father was not far away from me.
But I began to doubt my condition,
lest I should ascribe this serenity (which might become continual) to a growth
in the Truth and favor with my God before I had really attained it.
Thus I almost wished to feel my customary poverty of spirit again,
along with His chastening, believing myself to be far from perfect.

But now He has seen fit to change the favorable dispensation
into one that is more searching and trying,
often withdrawing His favor, so that I seemed neither "`carried on the side,
nor dandled on the knee.`"^
footnote:[Isaiah 66:12]
I will bear it; for oh, I dread "`being at ease in Zion,`"^
footnote:[Amos 6:1]
or trusting in anything short of what is really substantial,
which feeds and nourishes the soul unto everlasting life!

Fifth month 7th, 1810.--I have now arrived at my seventy-fifth year,
and in perusing again what has long ago been written
of the Lord`'s dealings with me in my childish state,
I feel the renewing of that ancient power which impressed my mind when I penned them;
so that I hope they are not words which will fall to the ground,
for they are faithful and true sayings.
Reader, if when you peruse them, a gentle summons should be heard;
"`The Master has come and calls for you,`" then rise up quickly, as Mary did.
Let others suspect what they will respecting your haste.
These are seasons when we are to "`greet no one along the way.`"^
footnote:[Luke 10:4]

There are many publications in the world.
Some of them have a tendency to corrupt the morals of those that read them.
Such as these have never come much in my way,
nor have I dared spend my time in reading them.
But there are other books that are deemed more innocent,
and these having been introduced into my family,
I have thought it right to view the nature of them,
and to consider what tendency they might have upon
minds that seemed to take delight in them.
And I have this to propose to the serious consideration of all, especially the youth,
or even those more advanced in our Society, to whom such books are pleasing.
To such I say: Read the Scriptures and other truly good books,
and observe the tenor of your minds while reading.
You will feel which of them draws the soul nearer to God--whether
it is these publications I have been hinting at,
or those that have been penned by the true witnesses of our Savior`'s life and death.

In the written records of His life,
we shall perceive where the Master`'s footsteps have trodden in deep humility.
We shall see His wounded side and the print of the nails, in the viewing of which,
living virtue seems to be felt.
Such authors, we must believe, have been with Jesus.
It was reading of His sufferings in my early youth that melted me, as before mentioned,
and bound me to His pure Spirit.
Oh! that all mankind saw it as I now do!
How fearful would they be of giving out money (which
might be better employed) for unprofitable publications.
Nor would they dare waste their precious time in reading such things.

Eighth month 6th, 1810.--I have been surprised that the older and more infirm I grow,
the more I am enlarged in mind,
and the more illuminated I am in regard to Scripture sentences.
Oh, how the watchword (when it comes) brightens upon my mind,
and inwardly gives an ability to see further into it.
It is the Lord`'s doing, and marvelous indeed in my eyes.
Lord, what am I, that You continue thus to acknowledge me,
and that You thus expand my heart in old age,
when the keepers of this frail building tremble exceedingly?
I am so humbled thereby as to consider myself abject, poor,
and unworthy of a place where the Majesty of heaven resides.
Oh, when this mortal shall put on immortality, and every seed receives its own body,
mine must surely be as of the lowest order of angels!
Sown in weakness, even if it be raised in power.
But cease, my soul, to pry into the secrets of eternity!
The lowest dwelling place in the Father`'s house will far, very far, surpass my services.
Oh Lord, be near at the winding up of time, is my sincere prayer.

Eleventh month 14th,
1810.--This day we had a very confirming season in our silent weekday meeting.
I thought I should never more doubt being under the notice of heaven,
the evidence was so strong,
and my love seemed so perfect towards God that it cast out all fear.
I neither feared death, hell, nor the grave.
The armies of the aliens, for the present, were entirely put to flight.
My faith was strong respecting my own well-being,
and I even had faith for those who gathered with me that day.
We seemed indeed come to Zion, the city of the living God,
and gathered in spirit with an innumerable company of angels.
Previous to this precious season,
I had had very great openings into Divine things pertaining to
another life--things so sacred as not to be meddled with--which
brought me to think I would soon be gathered to my rest.

In the weekday meeting I saw, as from the mount,
that the many trying seasons I have often been led into in our meetings, were necessary,
lest I should be exalted through the sublime revelations I have been favored with.
This did for me what the thorn in the flesh did for Paul,
and I now seem one of the least, and view myself in a truly abject light.

Monthly Meeting, Pardshaw Hall, 23rd of seventh month, 1811.--Being at Underwood,
I attended this meeting and thought it a very favored time.
The glory of the Lord, as it appeared to me, filled the house; and,
sitting upon the mercy seat, each seemed to have the gracious privilege of pardon.
It brought to my remembrance the apostle Paul when he was caught up into the third heaven,
and saw and heard what was not lawful for a finite creature to utter;
neither dared I to utter, on the side of mercy, what I then felt.
I thought that if I had thus continued under the immediate sense of God`'s presence,
I would neither have felt hunger nor pain.
But this was not a state to be continued in; and upon my return home,
the gracious presence was withdrawn.
I do not say a messenger of Satan was sent to buffet me,
but I was plunged into such heart-rending doubts respecting my own salvation
as thoroughly prevented my being exalted above measure because of the
abundant revelation that had been mercifully granted to me.
I did not see that I had erred in my communications to the Friends gathered,
for I had not kindled my own fire and warmed myself with the sparks thereof,
that I had thus to lie down in sorrow.^
footnote:[Isaiah 50:11]

Oh! Lord, I beseech You, keep me in Your patience,
and let Your refining power leave nothing that is wrong in me unsubdued!
You, oh Lord, know what I have gone through in my youth, and all along.
Your hand has been heavy upon me.
You, oh Lord, have often given me to see that You impute no iniquity to me,
but have given me a sense that I have full acceptance with You.
So "`Why are you cast down, O my soul?
And why are you disquieted within me?
Hope in God, for I shall yet praise Him!`"^
footnote:[Psalm 42:5]

In penning these remarks, I feel good to arise, which quite binds up my broken heart.
For although I indeed have heavy trials in the outward,
they have had no share in my present plunging.
It was because "`my Beloved had withdrawn Himself, and was gone.`"^
footnote:[Song of Solomon 5:6]
A dispensation of this nature would not have dismayed me so much,
had I not been so long in the ministry.
The Great Master, I thought, had fully tried me as to self-exaltation,
and proved that I dared not say, "`The Lord says,`" when He had not spoken;
so that I really hoped I had been established upon the immovable Rock.
But I find that they who think they stand must take heed lest they fall.
Neither are we to recur to those sublime discoveries which
the Divine light has previously manifested to us.
But rather, after experiencing great favor in spiritual vision,
we must allow all to return to the Fountain from which it sprang.
Ah then, how emptied and stripped we are!
For vessels that have been used must be washed.
And how unsafe it is for us to feed upon any good we have formerly been enabled to do!
We experientially find it to be a truth,
that it is not for works of righteousness which we have done,
but of His mercy we are saved--and that this is by the washing
of regeneration and the renewing of the Holy Spirit.

First month 29th, 1812.
Fourth-day--A precious meeting to me; indeed I thought the solemnity spread over all.
Oh, the pure silence I felt, as if Immanuel stretched forth His wings and covered us!
That sublime and exalted vision of the prophet was
brought clearly to the view of my mind,
when he "`beheld the Lord sitting upon His throne, high and lifted up,
and His train filled the temple.
Above it stood the seraphim, each having six wings; with two they covered their face,
with two they covered their feet, and with two they flew.
And one said, '`Holy, holy, holy, Lord God Almighty,
the whole earth is full of Your glory.`' And the posts of
the door moved at the voice of Him that spoke,
and the house was filled with smoke.`"^
footnote:[Isaiah 6:1-4]

I inquired whether I was to divulge it to those present, and the answer I received was,
"`It is favor and food for yourself, and if you give to others your own portion,
you will soon become meagre and thin.`"
I returned thanks, and gratefully acknowledged the favor granted,
and now conclude to keep hold of the confirming evidence I then had.
But fear at times assails me, lest I should lose it again and doubt.

Fourth month 5th, 1812.--After a time of illness this morning,
it was mercifully handed to me, as Divine consolation;
"`You are in the hollow of My hand;`" and again, "`The Lord is my shepherd,
I shall not be in want.`"
Oh, Lord, what an unutterable favor this is, when the weakness of my body, at times,
is as much as nature can bear.
I have passed thus far through the wilderness of this world in as great jeopardy,
as closely exercised, and as nearly fainting under my trials,
as perhaps any poor mortal ever did.
What an unspeakable favor,
when now verging to the confines of the narrow and silent grave,
that so unworthy a creature should thus be acknowledged!
Oh, gracious Father, continue Your preserving,
protecting care of me to the last moments of my life,
and I will laud and praise Your name while here, and forever.
Amen.

Sixth month, 1812.--Recovering from a recent illness,
I found an inclination to inspect my papers which were written under a religious sense,
and upon reviewing that extraordinary vision,
a fear impressed my mind lest any hereafter should
think I had exceeded the bounds of a finite creature.
Considering this it occurred to me, let them call to mind my deep exercises,
hard servitude, and bitter bondage in the iron furnace,
in a land of thick darkness which might be felt.
I was so marred that I became a wonder to my contemporaries.
Now after this,
if a gracious God saw fit to bow the heavens and come down
to touch my heart that it might melt--He being Omniscient--who,
after such great favor would lightly esteem the Rock of their salvation?
Although He is the High and holy One who dwells in the light and inhabits eternity,
yet we are assured that He condescends to revive the spirits of His poor, contrite,
humble servants, who tremble at His word.

Our blessed Lord and Savior Jesus Christ,
who is our Intercessor and Mediator between God and man,
when questioned why He would manifest Himself to His chosen ones, and not unto the world,
sealed the promise thus: "`If anyone loves Me, he will keep My Word,
and My Father will love him, and We will come unto him, and make Our abode with him.`"
This is not like a traveling man, that turns aside to tarry for a night,
and then is gone; but Christ takes up His abode with them as a blessed guest,
as "`a teacher`" at home within, "`that cannot be removed into a corner.`"^
footnote:[Isaiah 30:20]

These openings in my mind confirm to me a Divine communion; and I leave it now.
And if it be thought right to wholly suppress any part or all that I have written,
the will of Friends be done in the Truth.
For oh, I dread presumption!--knowing the high tree must be laid low,
and the low exalted; the green tree must be dried up, and the dry made to flourish.

Third month 14th, 1813.--A deep acknowledgment of the mercy of God.
As I lay in bed this morning,
under piercing anguish of mind on account of my grandson`'s departure from the Truth,
my spirit (though in the deepest affliction) was permitted to ascend,
I thought even to the Almighty`'s throne.
There I poured forth my soul on my own and his account,
and condescending kindness granted, in the abundant mercy,
to unveil His kind countenance and let me know that I ought
not to dispute the assurances He had given me of His favor;
and that if after all the evidences He had given me of His protecting care,
I should cast away my confidence in Him, I would be worse than an infidel.
Then a little hope was revived that the poor erring youth would yet be visited in mercy.
This view, if only tending to bind up my broken heart, or to heal my wounded spirit,
I accepted in thankfulness from my God.

Oh, gracious Father, in Your never-failing kindness,
keep this little flock (the members of this meeting,
amongst whom I have often labored) when I am no more.
May they never become a desolation, a breeding ground of nettles,
but continue to grow up in the nobility of Truth.
Dear Friends, nothing will do but keeping near to God,
and dwelling always as in His presence.
Do nothing in His sight that you would be afraid any mortal should see.
Keep a pure heart and clean hands, and your end will be peace.
I feel this love for the Monthly Meeting--for its members are dear to me.

Sixth month 2nd, 1813.--Upon returning home from our weekday meeting,
in which I had been faithful according to the vision and sense given to me,
this intimation revived: "`The Lord notices your shaking head and trembling limbs,
and in His own time, will set you at liberty.`"
A blessed hope then sprung up from this that, though sown in weakness,
I would be raised in power.
Oh, blessed be His holy name!--for He feeds the hungry with good things,
but the rich and full He sends empty away.

Our Monthly Meeting at Whitehaven, in the eighth month, 1813,
was to me a comforting season.
Nothing could be heard but the voice of thanksgiving and praise.
The grand adversary totally was overpowered;
not one cloud appeared to eclipse the glory of the day or dim the beauty of Zion.

Tenth month 21st, 1813.--I have had this day, at the weekday meeting at Whitehaven,
the most undoubted evidence of the overshadowing of Divine
love and mercy that I ever remember to have experienced.
Truly the wing of the Almighty might be said to be over us.
His reconciliation was offered, and on the side of mercy,
I saw more than I have freedom to write or speak.
Oh, my dear friends belonging to this meeting, especially those at meeting that day,
let us prize the Lord`'s goodness to our souls!
My love was such to you that it appeared almost insupportable that even one of
you should come short of the heavenly rest which I beheld was intended for us--far,
very far beyond the conception of any finite creature.

Tenth month 31st, 1813.--Oh,
the consoling visions I have experienced during my late confinement!
A tribute of thanksgiving and praise is richly due to my blessed Lord and Master,
Jesus Christ,
for the sense He has been pleased to favor me with
that He has heard my prayers for my poor grandson.
For a little before his death, the Spirit of intercession was poured forth upon me,
and my prayers were strong on his account.

Although I am exceedingly shaken, and my hand very unsteady,
yet if it is right for me to leave to posterity the memorable
condescension of the Almighty to me (a poor worm),
I shall be able to make it legible.
Upon the 13th of twelfth month, 1813, sitting in the evening by my fireside,
with company around me engaged in conversation, I felt a strong attraction heavenward,
which I was glad to feel.
And a gracious God seemed pleased to bow His heavens and come down,
directing me to dismiss every doubt respecting my own exit;
for He would take me in His mercy and support me through what might befall me.
And my charge was to never more doubt of my eternal rest.
Also respecting my grandson, I was told to doubt no more,
for repentance had been granted even to him at a late hour.^
footnote:[This poor young man was confined to a sick
room in the military hospital at Chelsea,
with many others in the same apartment, which he very much regretted,
because he could not attain to that quiet state of mind which he much wished for.
He was brought to a sense of his missteppings,
and expressed the distress he felt for the uneasiness he had occasioned his grandmother,
fearing he should shorten her days; and was very anxious to read his Bible.
He uttered some striking expressions near his close, which are not clearly remembered,
but the day and hour of his death corresponded with the comforting
impressions that his grandmother had received respecting him.]
The Spirit of intercession was poured forth upon me with
such energy as seemed to rend the very heavens.--O my soul,
never forget this season,
nor ever cease to extol a merciful God in pardoning transgressors!
In this instance, mercy has covered the judgment seat to a hair`'s breadth.

The Almighty`'s presence was so full and confirming,
that I found it as much as my frail tabernacle could bear and live.
I then experienced that no flesh could see Him in His majesty and live.
Although once before I had been in a somewhat similar situation,
yet I had not the sense given to me at that time that if Divine favor increased,
my body could not retain the spirit.
I now desist from exposing myself further,
feeling overcome with the present extension of grace.
Oh, gracious God!

First month 16th, 1814.--This day after Friends had gone to meeting,
I was very low in mind; when the words of the prophet came very livingly to me,
that the Lord would "`make the parched ground as a pool.`"^
footnote:[Isaiah 35:7]
And after sitting in this disconsolate manner, I was comforted with;
"`I am near you, though you know it not.`"

Eighth month 4th, 1814.--Oh,
the mercy of a gracious God to me in my old age and great bodily infirmity,
who has given me to experience this morning that "`the just live by faith.`"
Were it not for this precious faith, I should conclude myself on the brink of falling,
almost every moment.
Oh, blessed is Your holy name forever!

Ninth month 19th, 1814.--This morning I again had the most strengthening,
consoling evidence of Divine favor that my poor frame
could bear--letting me know that as my strength decreased,
His watchful care over me increased.
And although He has seen fit nearly to deprive me of my outward hearing,
He has increased the inward so surprisingly that I often seem to fall
down before Him in astonishment--my mind being so expanded and enlarged,
that as naturals abate, spirituals increase,
and my dear Redeemer allows me at seasons to repose as upon His bosom.

[.asterism]
'''

[.emphasized]
After this, Jane Pearson wrote no more for public inspection.
Yet for many months, though in great debility and bodily pain,
she continued to converse with her friends,
most frequently respecting the goodness of the Almighty.
Not many weeks prior to her decease, upon a Friend`'s departing from her,
she seemed affected, and said, "`Though I drop tears, I am not left comfortless.
No; we have not followed cunningly devised fables.
I think what I now feel might convince the whole world.
Oh, it is marvellous! It is marvellous!`"
It appeared to those who were with her at her death
that the last effort of her pious life was prayer;
but the words could not be clearly heard.
She quietly departed about three o`'clock, the 20th of second month, 1816,
aged eighty-one, and a minister in the Society of Friends about forty-two years.
