== Introduction.

When those we have loved and looked up to are taken from us,
whatever belonged to them becomes enhanced in its value.
When their Christian example is withdrawn,
we often thoughtfully return to the circumstances of their conscientious lives;
when we can no longer listen to their cheering conversation,
we tenderly recur to their affectionate sayings;
and when we hear no more their religious exhortations,
to the written records of their devout minds we are glad to have recourse,
as precious monuments of departed piety.

These observations will apply with propriety to Jane Pearson,
the subject of this short memoir.
In her last letter to the writer,
she expressed a desire that he might look over her papers when she was gone,
and dispose of them as he thought best.
The use he is now about to make of them, if he is not mistaken, the reader will approve.
These memorandums of her pious mind, were all in her own hand-writing,
and appear to have been penned under lively impressions.
Among her papers were also found several copies of verses;
and as it will probably be acceptable to the reader,
a specimen or two will be given in the memoir.

Of her religious experience, an opinion may be formed from her writings;
and of her religious services, from the testimony of Pardshaw Monthly Meeting,
which is introduced at the close of her own memoirs;
yet some readers may be inclined to know more of her general character,
and how she appeared daily amongst us.

As a reverence for the Divine Being was the leading feature of her mind,
so the solemnity of religion was never lowered in her conversation.
To some she might appear reserved; for as she has told me,
when in her walks she met with acquaintances, she could not like many,
stop and hold a discourse with them which meant nothing.
From these and other circumstances,
her deportment might sometimes appear distant and restrained;
but in the circles of her friends, there were few that unbended more freely.

On such occasions, her sentiments and even the tone of her voice,
had as much the hearty expression of sincere good will, as any one I ever met with,
whilst her innocent cheerfulness with youth,
and her entering most kindly with them into their little concerns,
endeared her to this class, both as a mother and a chosen companion.
She was qualified for a companion in the foremost ranks of virtuous society;
yet to those in the humblest sphere, she spoke with affection and kindness:
indeed I have rarely met with one in whose deportment were united such dignity and sweetness.

She seemed to retire from a thoughtless world, to live in sweet seclusion with her Maker;
and those who were set forward on their heavenward journey,
she hailed as fellow travellers towards Zion: to her sisters in religious fellowship,
who went forth in humility and simplicity to advocate
the cause of righteousness amongst men,
she held out the language of endearing encouragement.

Of her own ministry it might be said, that it was plain, powerful, baptizing and new.
When I say new, I hope none will suppose I mean that she had any new doctrine to preach;
for the ministers of Christ have no new principles to set forth.
I mean by new, that her ministry was in the fresh openings of life.
I do not covet abundance in our meetings; a few wholesome crumbs,
a little fresh water from the pure spring, satisfy me;
yet I do not wish to avoid the piercing of that Divine power,
which would divide between those things that please
the Almighty and those which please him not;
since such a division must take place, or heaven will not be our portion.

Her disposition was modest and retired; yet the reader will find in the following pages,
that for his instruction and encouragement, she has in the sincerity of her heart,
spread before him some of her mental trials.
The conscientious mind, longing to be united to Divine purity,
has sometimes sore conflicts with the evil principle within;
but when through the power of the grace of God, evil is overcome,
the conflict is succeeded by unspeakable joy.
This, I trust.
Christian statement, it will appear, was verified in the experience of our beloved friend.

That a truly religious mind is assailed with trials,
we see from her own undisguised account.
These trials arise from various circumstances;
perhaps at times to prove the foundation of our faith; at other times,
from a fear of not obtaining what is of all things most desirable,
acceptance with the Almighty.

But it may be, that the greatest of all are the trials which are needful,
when a vigorous understanding and warm affections are to be turned
from their natural tendencies into pure obedience to the Almighty;
to become fit instruments for proclaiming his Divine will.
This is like death; like the breaking up of nature, that the soul may become free,
and prepared for entering the holiness of heaven.
This at the time is hard to be endured; but it is followed by joy, peace,
and unspeakable satisfaction; for surely, above all else to be experienced here,
is the enjoyment of Divine favour to a pure mind.

The reader will find something of all this set forth in the following pages,
and may read therein a profitable lesson in spiritual religion; though with myself,
he may not have attained to the assurance of acceptance, like her whose work is done;
yet let us not forego our confidence;
but in humility endeavour to continue steadfast in the faith.
This will be like an anchor to our minds,
so that when others are tossed with the troubles of this world,
we may be favoured to hold our lot in peace.

It appears from the testimony of those who knew Jane
Pearson during the greater part of her life,
that a solicitude for the glory of God,
joined to a care for her immortal part and the future well-being of her fellow creatures,
was with her paramount to all other considerations.
This is true piety.
To these ends she laboured in public and in private;
and dared not to shrink from her testimony for God and his righteous law,
by suppressing what came before her.
Though of a tender and affectionate disposition,
she did not withhold the just denunciations of truth against iniquity.
She did indeed pity the individual,
- but she sounded the alarm in the ear of the transgressor;
yet to those who were awakened to a sense of their sins,
she joyfully announced the terms of reconciliation.

Early in life she married John Pearson of Graysouthen,
by whom she had three sons and four daughters;
whom she watched over with the tenderness of a mother;
anxious that they should walk in the paths of innocence and virtue,
and in the holy religion of our dear Redeemer.
Two of her children died before her husband,
and the others followed him to the silent grave,
while she remained to mourn with many tears.
Deprived of the attention and support of her husband and of all her children,
it might be supposed she would sit sorrowful and alone under her afflictions;
but her age was cheered by two affectionate grand-daughters;
and her mind being reconciled to the dispensations of Providence,
her disposition was not soured by her trials, but even at the latest period of her age,
which exceeded eighty years, in the company of intimate friends,
her conversation and manners partook of the pleasantness and cheerfulness of her prime.
Her letters too were occasionally lively,
but more frequently fraught with deep instruction.

The compiler was but a youth when he first saw his excellent friend;
which was at a Northern Yearly Meeting, when her ministry impressed his mind.
Several years elapsed before he spoke to her;
and he little thought that a faithful friendship would spring up between them.
She then had an uncommonly fine person; but it may be said, that her mind was superior,
being concerned for the glory of her Maker and intent on fulfilling his Divine will.
Her labours are now closed, and we may believe she is receiving her reward,
in that state of purity and peace, after which her soul longed while on earth.

It is a serious consideration with the compiler,
who is often doubtful whether he has passed "`the straight gate
which leads to life,`" to trace the steps of our pious friend,
into the valley of humiliation and discouragement,
or to pursue her way in the ascent to the heavenly Jerusalem,
and set forth the Divine prospects she beheld there.
Diffident of his own judgment, how far these things are within his province,
he forbears to enlarge, leaving her own remarks to speak for themselves;
but on another point he is inclined to express his opinion more
freely.--Some minds may be disposed to doubt the foundation of
what is advanced in some parts of the following pages;
to such the compiler would say,
he has long been fully of the persuasion that immediate revelation has not ceased.
He believes that the same Almighty Power who presided at the time of Pentecost,
who visited Zacharias, Ananias, and Cornelius; continues to manifest himself to this day.
Believing this, and knowing the superior mind and uprightness of the individual,
concerning whom he is now writing,
he has no difficulty in believing what she has recorded.
If any praise is due, let it not be ascribed to her,
but to Him who is the Author of all good.
This was the fervent desire of our departed friend, in which she is followed by,

[.signed-section-signature]
Thomas Wilkinson.

[.signed-section-context-close]
Yanwath, Seventh month, 1816
