[#testimony.style-blurb, short="Testimony of Pardshaw Meeting"]
== The Testimony of Pardshaw Monthly Meeting in Cumberland, concerning Jane Pearson

This our dear and ancient Friend, was the daughter of Jonathan and Jane Sibson,
of Newtown, near Carlisle, at the former of which places she was born, in the year 1734.
Her father dying when she was very young,
the principal care of her education devolved upon her mother, who, we believe,
being conscientiously concerned,
that she might faithfully discharge such an important trust,
gave her a guarded and religious education.

In early life she was strongly inclined to gaiety; but by submitting to the powerful,
heart searching operations of Divine love, clearly manifested,
those natural propensities were brought into subjection.

About the eighteenth year of her age,
she accompanied through this county a female Friend,
then upon a visit to the meetings of Friends in these parts.

In the year 1757, being about twenty-two years of age, she was married to John Pearson,
a religious young man of Graysouthen, within the limits of this meeting.
In the course of several succeeding years,
she passed through various deep baptisms and refining operations;
and thus becoming obedient to the forming hand, she received a gift in the ministry.
She came forth very acceptably in public testimony, about the year 1773.

In the following year her husband was removed by death,
leaving her with a numerous family of children, some of whom died in early life,
and the rest at different periods, after having attained to years of maturity.

Thus she had deeply to partake of the cup of affliction,
and to become acquainted with sorrows; but relying on the mercy and goodness of Him,
whose ways are all in unerring wisdom,
she was supported through these trying and afflictive dispensations;
and we believe she was favored to experience that state of
perfect resignation and acquiescence to the Divine will,
in which she could truly adopt the language of a tried servant of old: "`The Lord gave,
and the Lord has taken away.
Blessed be the name of the Lord!`" ^
footnote:[Job 1:21]

Though she did not apprehend it to be required of her
to travel much in the work of the ministry,
yet she was not wholly exempted from this service.

In the year 1777,
she visited generally the meetings of Friends in Westmoreland and Lancashire; in 1779,
those of Westmoreland, Lancashire and Yorkshire; and in 1787, those of Lancashire,
Cheshire, Shropshire, Worcestershire, Warwickshire, Somersetshire,
Devonshire and Cornwall.
Her Gospel labors in these visits were, we believe, very acceptable,
yielding to herself the consoling reward of peace.

About this period she removed to Whitehaven, at which place she has since resided.
She was diligent and exemplary in the attendance of meetings.
Her ministry was sound, lively and edifying; and though her appearances were frequent,
and sometimes large,
she was particularly careful not to go beyond the pure openings of the holy Spirit.
In prayer she was remarkably powerful and fervent.
She was a truly affectionate parent and friend; tenderly sympathizing with the afflicted.
In conversation lively, affable and instructive;
being endowed with an excellent understanding.
She retained her natural cheerfulness even to very advanced years,
and her mental faculties unimpaired to the last.

Sometimes she intimated the serenity of her prospects,
when the trials and exercises attendant upon humanity should terminate.
Not many weeks prior to her decease, upon a Friend`'s taking leave of her,
she seemed affected, and said, "`Though I drop tears, I am not left comfortless.
No: we have not followed cunningly devised fables.
I think what I feel, might convince the whole world.
Oh, it is marvelous! it is marvelous!`"

At another time she requested that her two granddaughters, being all the family she had,
would not grieve after her; but rather rejoice,
that she was relieved from all her sufferings; "`for I believe,`" said she,
"`that at my dissolution, death will have no sting, nor the grave any victory.`"

Second month 17th. Being much tried with infirmity and pain,
she said with earnestness to those about her:
"`Join with me in petitioning the Father of mercies, to relieve me from my sufferings:
Oh, that I had wings like a dove; for then I would flee away, and be at rest.`"

In the morning of the 18th, being in great bodily pain, she exclaimed: "`My God, my God,
forsake me not now.`"
She was soon after seized with faintings.
In a little time she revived,
and affectionately noticed some Friends that had come to see her.
On the 19th she slumbered much and said but little.
Very early the next morning her cough became troublesome, and her breathing much affected.
About this time she was thought to be exercised in prayer,
but the words could not be gathered.
She quietly departed about three o`'clock the same morning;
and we have no doubt but her pure spirit, released from the shackles of mortality,
ascended to the celestial mansions,
to receive a crown of righteousness and an inheritance incorruptible,
that will never fade away.

Her remains were interred in Friends`' burial-ground, in Whitehaven,
on the 25th of second month, 1816, after a large and solemn meeting.
She was about eighty-one years of age, and a minister about forty-two years.

Read and approved in our said meeting, held at Cockermouth, the 19th of third month,
1816; and signed on behalf thereof, by John Wilson Fletcher, Clerk to the meeting.
And on behalf of the women`'s meeting, by Deborah Robinson, Clerk.

The foregoing testimony has been read and approved,
in the Quarterly Meeting for Cumberland and Northumberland,
held at Carlisle the 28th of third month, 1816; and signed on behalf thereof,
by Thomas Stordy, Clerk.
Signed in and on behalf of the women`'s Quarterly Meeting,
held at the same time and place, by Lydia Sutton, Clerk.

[.asterism]
'''

=== Conclusion

Jane Pearson has finished her outward labors and inward exercises;
and the reader has now finished her own memoirs, here presented for his perusal.
Everything pertaining to this life, whether conspicuous or obscure, must come to an end;
but there is a life beyond the grave, that will continue forever.
To engage us in a preparation for that life, our friend has written;
to none of her readers, may she have written in vain.
As for herself, it has been seen, that under accumulated discouragements,
she sought for the evidence of final acceptance;
and that her constancy was crowned with the assurance she sought for.
This ought to animate the diffident and encourage the dejected.
By her life, the lukewarm may be also reminded,
that though we may be born members of our religious Society;
yet having by nature the same propensities as others;
we must be "`born again,`" if we would become members of the church of Christ.

We have also seen that the journey through time, of our dear deceased friend,
was in the path of tribulation.
Independent of her sorrows as a widow and a mother,
her "`inward conflicts`" and "`searchings of heart,`"
were equal to most that we read of.

Modest, diffident and humble, how came she then to expose her trials?
Surely it was for the benefit of others;
and to bear a testimony to the goodness of God in sending the Comforter into her soul,
as promised by a dear Redeemer.
These things set forth by her own pen,
have a value in them beyond what could be produced by the pen of another.
In laying down mine, I am inclined to say,
Oh! that more full obedience was yielded to the power of Truth,
through the various ranks of our religious Society;
I include myself in this implied shortness; and my belief is,
that it would then rise in its early simplicity and brightness.
