== Section 1

[.chapter-synopsis]
* Her reasons for writing some memoirs of herself
* Her birth and parentage
* The state of her mind in very early life
* Her resolution not to open her mouth in the ministry
* Her marriage
* The deep inward conflicts she endured for not resigning herself to Divine disposal till she was made willing to obey
* Her first offering in the ministry
* Her remarks on this important office.

It has long remained with weight upon my mind,
to leave a few remarks respecting the Lord`'s dealings,
when He was pleased to lay His hand in judgment upon me, for my backslidings;
hoping it may be of service to some poor, tossed, afflicted, tempted, bewildered mind;
for I do believe it would have been of service to me in my painful moments,
to have beheld the footsteps of others, if I had had stability to read,
or quietness of mind to be instructed; which for a time I had not,
being feeble and sorely broken,
bemoaning myself by reason of the disquietude of my heart.

I was born at Newtown, near Carlisle, of sober, religious parents.
My father dying when I was young,
I had more experience of my mother`'s religious care in our tuition.
She was left with four of us to bring up;
and her zeal and care for her offspring abated not;
so that I have a good account to give of her pious solicitude and concern for us.
On that account, she hired a schoolmaster in the house, to teach her children,
to prevent our being corrupted,
or learning the improper customs of the people amongst whom we dwelt;
so that we were kept, more than many others of our age,
from associating with those of other persuasions.

It pleased the Lord by His good Spirit, to work in my heart in my young years;
which brought a godly sorrow over me,
and a fear lest I should be taken away in my childish follies.
When the bell used to toll for those of other persuasions,
oh! the awe and inward fear attendant on these occasions!
I would say in my heart; these are now called off the stage of this world,
and fixed as forever they must be.
My solicitude at times so far prevailed,
that I was desirous of knowing the age of the deceased,
and whether they were of ages similar to myself; and if they were, it added to my fears,
which at that time were piercing.
But if they were further advanced,
I endeavored to appease these fears by considering myself young,
and that I might escape such a removal in youth; for I was afraid to die,
and that awful "`forever and ever,`" brought sadness over me.

I loved to read the Scriptures, especially the New Testament;
and when I read the passage,
where our blessed Lord is described as having suffered so much from the high professors,
who despitefully treated Him and crucified Him, it afflicted me deeply;
and I believed I should not have done this:
so my heart became melted and tendered under a sense of it.

About this time it pleased the Lord to send into our parts Mary Kirby,
a minister of Norfolk; and she being alone, requested me to accompany her.
My mother gave me up, and it was a time of reaping some advantage;
for when I returned home,
I felt my heart in a good measure cleansed and emptied of the old inhabitants;
my stiff will being measurably subdued; and loving retirement,
I was drawn from my old companions.

I then witnessed a state of deep poverty of spirit,
which caused me thus to address the Almighty: "`Lord! what would You have me to do?`"^
footnote:[Acts 9:6]
At that time I did not know there was any thing in my conduct which displeased Him;
but His word in me was,
"`I must not only cease to do evil, but I must learn to do well.`"^
footnote:[Isaiah 1:16-17]
Thus I experienced, when the unclean spirit is gone out, we walk through dry places,
seeking rest but finding none.
Oh! that this time of drought and emptiness was but patiently abode in!
But when all the old inhabitants are cast out,
the creaturely part is apt to catch at something, to make up the loss it has sustained;
for how hard is it to live without life in the creatures, or externals!
The senses are continually seeking for something to heal this deadly wound,
and to replace somewhat in an emptied mind; for it is hard thus to die to self.
Therefore many are apt to connect themselves again with those worse than themselves,
and their last state is worse than the first.

I feel such heavenly serenity in my endeavors to bring together these few remarks,
which have long lain among my papers,
that I have no doubt it is right for me to leave them to posterity;
having a living hope in my heart, that the perusal of these faithful sayings will,
under Providence, tend to reach and reduce the uncircumcised Philistine nature.
The infirmities attending my family in my younger years, kept me much at home;
and now my own weakness and infirmities are great and many.
Nevertheless my love is true to the great and good cause,
and I should be willing to go the world over to edify the body,
and promote the reformation of mankind, and the redemption of their souls,
through Jesus Christ.

I continued to have this deep sense of privation and emptiness.
I was sitting in our women`'s meeting for discipline at Carlisle,
when it appeared clear to me, that if I continued thus inward with God,
I should soon have to speak to others.
This intimation that I was to be drawn to do well, was so far from humbling me,
that I did not even desire to be excused,
or pray my Divine Master to have patience with me: but I resolutely said;
"`I never will do so.`"
I started aside like a broken bow,
and I believe went into greater alienation from
the Divine life than I had ever done before;
and just it would have been, if Infinite Wisdom had cut me off in my disobedience.
I was guilty of many wrong things, which brought heavy judgment on me;
and living with an aunt at Carlisle, I was much exposed; she keeping a shop,
and I being from under the strict eye of my mother.

I was now about the seventeenth or eighteenth year of my age.
Through every dispensation, I had a great love for good Friends;
and they often manifested love for me; owning the valuable part in me,
and overlooking that which was rebukable, I doubt not,
in the faith that the Lord would carry on His own work;
and their open carriage towards me, was so far from begetting disesteem in me,
or inducing me to account them undiscerning, that it wrought upon the better part;
for indeed I could have washed the saints`' feet.
Ministering Friends lodged at my mother`'s, and I sometimes got the blessing,
which is fresh with me to this day.

At the age of between one and two and twenty, I was married to John Pearson, a sober,
religious young man.
About a year after my marriage, my false rest was broken; though I was rightly married,
and I trust in best wisdom.
United to a choice husband, I swam as in an ocean of pleasure; but I witnessed,
instead of peace on earth, a heart-piercing sword.
My undone condition was present with me day and night, when awake.
Indeed I slept but little; sleep departed from my eyes and slumber from my eyelids;
so that when night came, I wished for morning.
And though I had been preserved from gross evils,
so heavy was the Lord`'s hand in judgment against the sinful, impure part in me,
that there was sufficient work for His heart-piercing sword,
which divides between the precious and the vile, that which serves Him,
and that which serves Him not.

In my own view, my case was now exceedingly deplorable;
so that I neither ate nor slept much, which occasioned a visible decline in my health.
Indeed I was a wonder to behold; the people wondering what had befallen me.
The enemy followed me closely with most grievous besetments;
things that my very soul loathed would he charge upon me to be my own: and I,
not having strength to resist, with a "`Get behind me, Satan;`" or on the other hand,
experience to distinguish what proceeded from the enemy and his grievous insinuations,
and what arose from the weakness of nature;
every thing in me appeared out of order and a confused mass.
I did believe none ever was in such a state before;
nor had I ever read of any of our Friends who I thought
had gone through such various trying dispensations,
what if I say for fourteen years,
in which I feared I should never get to the better side.

I ate my bread weeping, and mingled my drink with my tears;
I was as if amongst fiery serpents, and in the jaws of a devouring adversary,
who was exulting over me; insinuating that the next temptation would sweep me away;
and darting things into my mind, one after another,
as swift as thought and as dark as the darkest night.
Oh! that my troubles were written with an iron pen and lead in the rock forever,
for surely they are far beyond my power of description;
and had not mercy been extended to me in this trying season, truly I had fallen.
The dispensation was so severe, that I could not tell how to live under it;
and I wished the Almighty would, by an act of His power, snatch me from mortals,
though it might be by an accidental death; for I still believed that if He did take me,
it would be in mercy.
So earnest was I after holiness and virtue,
that I often besought Him that He would never permit me to sin against Him,
that I might not be eternally ranked with unclean and abominable spirits,
which my very soul loathed.

I now abhorred myself as in dust and ashes,
because the enemy was thus permitted to assault me.
But through all, my intellect was preserved clear, and my reason sound.

About this time I was much drawn inward in prayer; for truly my tempted,
bewildered state called for it; and for a time, I believe I prayed without ceasing;
and yet the Lord knew what I needed, to fit me for His work and service, and now,
for my further refinement, He permitted the enemy to come still nearer;
although I might say with one formerly, "`Why does He yet find fault,
for who has resisted His will?`"^
footnote:[Romans 9:19]
This was one of the closest trials I ever met with:
one evening when the enemy accused me of evil,
and I turned in prayer to the Judge of all the earth,
making my appeal that He knew I was not wicked,
beseeching that He would rebuke the devourer for my sake,
and set me at liberty to serve Him; it was darted as quick as lightning,
"`There is no God!`"
Oh! then how did I mourn! believing there was none who had the least remains of good,
that was ever tried in this manner.
I thought I was now sinning against the holy Ghost,
and that I was the most wretched creature upon earth;
and the enemy followed hard with his bitter whispering,
"`To what do you pray? There is no God.`"

I never opened my case, under this dispensation, to any one;
for I believed whoever I opened my mind to,
would suppose I had been guilty of some gross thing, and therefore was a castaway;
and I thought if I met with discouragement,
I should not be able to bear the Lord`'s hand in judgment,
because I had sinned against Him.
At length I witnessed the truth of that declaration:
"`When Your judgments are in the earth,
the inhabitants of the world will learn righteousness;`"^
footnote:[Isaiah 26:9]
for truly I did experience inward purity of heart and cleanness of hands;
and in the Lord`'s own time He gave access to His throne;
and the spirit of prayer and supplication was poured out upon me, with a,
"`Verily there is a God that judges in the earth:`"^
footnote:[Ps. 58:11]
I then felt a holy sense of this truth, "`The Lord lives,`" and
"`because He lives, I live also.`"^
footnote:[John 14:19]

This dispensation, when it had prepared the way of the Lord and made His paths straight,
passed away, and I had now to say, the Lord lives, and I speak not falsely,
because I know what that precious knowledge of God has cost me.
I note these things for the help of any that may be tried as I have been;
for if I had met with any such account it would have relieved me.
There may be testimonies of Friends in the account of their lives, somewhat similar,
but I had not read them or they had gone from me.
Nor could I believe that any who were under the Divine notice,
or the turning of the holy Hand,
were permitted to abide so long a time under such dark bewildering suggestions.

May all who are thus proved, believe that way will be made for their escape!
Do not despond nor cast away your confidence!
I feel united to the suffering seed wherever they are,
or of whatever society they may be: I mourn with those that mourn,
compassionating their distress.
My commiseration and tender feeling is towards these; and I can address them,
not from any degree of experience to boast of, but from the depth of humility, can say,
"`Trust in God.
He can set His seed at liberty and will do it.`"

I now began to have great scruples respecting my wearing apparel,
as also that of my children, and the furniture of our house,
and coveted to have all things enough in the simplicity.
I thought of John`'s raiment of camel`'s hair, with a leather girdle about his loins,
and that his food was locusts and wild honey.
There was no delicacy here, either in eating or apparel.
Whatever the strong will in me seemed to loathe, or have an aversion to,
into that very thing, in the cross, was I led;
though it seemed an indignity to my very frame and disposition,
which was not thoroughly redeemed from nicety and a
desire to be somewhat in the eyes of the world.
Thus I was led till my will was subdued; and I was simple enough,
through being mortified every moment;
for I had always some scruple upon my mind whether things were right or not,
till I was rendered flexible and docile,
ready to take any impression the Lord would stamp upon me;
and I pray it may be that of holiness, during my stay in mutability;
and afterwards may I join the triumphant church,
praising the Lord God and the Lamb forever and ever.

About this time, I began to have some light and life about me.
I could not have believed that I should be so clear of
the bitter whisperings and insinuations of the crooked,
piercing serpent; it being natural to conclude, when things are so out of order,
and the adversary has effected such an inroad into the mind, making a prey of it,
that things will be hard to set to rights; but it is the Lord`'s work,
and He shall have the praise, for all is due to Him, and nothing is due to the creature.

I measurably witnessed an overcoming, and a little of getting the victory;
the head of the serpent being bruised, the accuser cast down,
and his accusations silenced, being acquitted of his false high charges against me;
and in lieu thereof I obtained a precious feeling of justification:
all old things being done away by that baptism which saves, all things became new,
and all things of God.
I now began again to have some view that I must tell to
others what the Lord had done for my soul;
how He had plucked me out of the horrible pit, out of the mire and clay;
letting me feel the sure foundation, and that I was to keep upon it,
and to proclaim the new song that He would put into my mouth.

This was a day of close trial; for I was brought to the test,
whether I would keep my covenant that I had made with the Lord,
in the days of my deep distress; which was,
that if He would but set me clear of the enemy, command what He pleased, I would obey,
let it be what it would.
In assembling with the Lord`'s people,
and it was a favor to me that I was amongst a living people,
our meetings were often favored with lively testimonies.
On such occasions,
Scripture sentences would impress my mind with some degree of life and power,
and according to my infant state and inexperience,
I felt some concern of mind to declare them to the audience,
though the evidence was not so full and clear as
my diffident mind requested and really needed;
for I was desirous that I might be preserved from saying
"`the Lord says; albeit, He had not spoken.`"^
footnote:[Ezekiel 13:7]

This caused a strong conflict, a trying of the fleece wet and dry;
my natural timidity closely adhering to a corresponding care not to cast untimely fruit,
which soon comes to decay.
This made me very wary and cautious,
as I believed many had taken the preparation for this office to be the commission,
and so had been dwarfs.
On the other hand,
the remembrance of the covenant I had made with the
Lord in the days of my sore bondage and deep captivity,
and my now not answering His requirings, made this a time of deep wading for me.
In meetings, matter would arise and spread in my mind towards the people,
and yet I felt not the command.
Oh! if any should be thus tried, if they are resigned and have minds devoted to the Lord,
to such I would say,
"`Fear not; the time will come, when you will not doubt respecting the Lord`'s will.`"

I was about nine months under this trying dispensation.
It wore down the bodily strength; my knees were weak; my flesh failed,
though not with refraining from food; my face was often sorrowful through much weeping,
and on my eyelids sat the shadow of death, through these winnowing, sifting seasons.
Yet through all, I had a little hope, which as an anchor stayed my soul,
and raised a holy belief that He who was my confidence,
would in His own time unfold the mysteries of His kingdom and give an undoubted evidence,
with unsullied clearness,
that it was His will the candle He had lighted should be set on the candlestick,
to give light to those around.
Thanks be to His ever worthy name, He fulfilled it; so that when the right time came,
in which I was to open my mouth in public, I had no doubt of its being His mind and will:
yet, through fear, I reasoned it away, but was not severely chastened for it,
as my heart was steadily purposed to serve Him; the will to do good was present,
but in the performance I felt weak; so the Lord forgave me,
and my mind enjoyed good till next meeting day.
I then went in great fear, to our little meeting at Graysouthen.
A few words presented lively, and I well remember the subject; the purport of them was,
that if we were but more inward in meetings,
they would be more favored than we often found them to be.
And is not this a truth at the present day.

My being thus cautiously led in the beginning,
has been helpful to me through the remaining part of my life, as to the ministry;
in watching against false views and presentations,
or taking the imaginary part for the revealed will of God.
Oh! the peace that I felt that night, after that short testimony.
It would have been acceptable to have been dissolved and to have been with Christ,
which is far better.

I had now great peace of mind, so that instead of my heart being a place for dragons,
for owls, and for screech owls, for cormorants, and for bitterns;
there began to be a melody in it, as it were the voice of the Son of God,
whose countenance is comely; and the myrtle, the box, and the pine,
sprang up in that heart which had been a breeding place for nettles.
This is the change that is wrought in man by being born
again of the incorruptible seed and word of God.
This was the change that was wrought in me.

I was frequently engaged to speak in meetings, and had satisfaction in so doing,
and Friends did not discountenance me in my little childlike movings; but approved,
though with a godly care.
And through abundant mercy, I moved in my gift in simplicity,
and did not choose for myself, nor seek for openings,
nor dress my matter according to the creaturely will,
neither dared I to restrain openings; all which are unsavory.
The Lord taught me to let it go just as it came;
though with blushing I may acknowledge that I lay very near a right-hand error,
if I may so term it.
Great were my care and fear, in joining with first prospects;
although they might be such as to lead me to conclude,
"`Surely the Lord`'s anointed is before me;`"^
footnote:[1 Samuel 16:6]
yet they have passed by, and a query has arisen, "`Are all your children here?`"^
footnote:[1 Samuel 16:11]
A proper query this;
for those who labor for the good of others ought to
have an especial care over their own household.

It often happens that the anointing is witnessed on the lesser appearance, a single,
seemingly a poor sentence, not produced till the last,
and scarcely worth ranking with sublime unfoldings, high in stature;
all the rest passing by: "`Send and fetch him, for we will not sit down until he come.`"^
footnote:[1 Samuel 16:11]
Oh, then the holy command goes forth, "`Arise, anoint him, for this is he;`"^
footnote:[1 Samuel 16:12]
and at some of these seasons, the horn has been filled with oil.
But this care, though laudable, yet prevailed often so as to keep lively openings,
till the tide of good was receding to the fountain or source from which it sprung;
and so the testimony was not so demonstrative and explicit,
as otherwise it might have been; producing a half strangled though living offering.
Read, you that can understand, and escape this rock on the right hand;
for by this conduct, I often broke our ranks in the ministry;
mine that should have gone first, being kept until the last.
Little vessels floating sooner than those of deep service and heavy burdens,
by getting out of the way of these, make their passage easier and safe.
If any were more forward than myself, they opened the door, and I,
through an unavailing trying of the opening,
would close it and be excused from meddling.

As I had a great love and care for the blessed cause,
that it might not suffer through weak advocates espousing it,
so I always thought lowly of myself, and by keeping back as above mentioned,
I became the author of confusion and disorder; the people were not so edified,
nor I so comforted, as might have been expected, from the conflict I had undergone.
I believe this had some foundation, in wanting to have a form of sound words,
that none could condemn: for though I did not seek openings, or dress them as I pleased,
yet all must have a mode of expression suiting the matter,
and to convey to the audience their sentiments on religious things.
On this ground, I wished to have the little matter set in order,
for I feared being taken to task for misquoting or misapplying the holy Scriptures.
But I was led clearly to discover that the ministers of Christ must rise,
when perhaps but a word is given them,
and minister according to the ability with which they are favored,
not at all fearing man, whose breath is in his nostrils,
but serve and fear the Lord only.
