== Section 2

[.chapter-synopsis]
* Her family Loss of two children
* Decease of her husband
* Her testimony concerning him
* Decease of her only remaining son
* First journey in the work of the ministry
* Decease of her mother, father-in-law, and daughter Hannah
* Visits Lancashire, Cheshire, etc., and some Western counties
* Decease of her second daughter
* Removal to Whitehaven, 1791
* Decease of her youngest daughter
* Observations at various times, to the year 1795
* Her exercise respecting vocal supplication in meetings.

I now began to have great outward trials, when there was an abatement in the inward.
I had an affectionate husband, who in my infant state bore part of my sufferings.
I had seven fine children, four girls and the youngest boys.
Till this time the Lord had made a hedge about us and all that we had.
Though we had not much to begin the world with, we increased fast in temporals.
It pleased the Lord to remove two of my youngest children by the smallpox,
in a natural way, as we could not be free to inoculate for it.
I grieved much that a breach was made upon us; indeed I fretted too much.
There was then a language proclaimed to my inward ear,
if I did not cease inordinate grieving, I should have more troubles.
The affectionate part was strong,
yet I trust I did not murmur against the dispensations of unerring Wisdom.
In the next year my beloved husband was taken from me!
Oh, I could then have parted with all my children to have had him spared;
for in him I was so bound up, that I believed if he died, I could not live.
He was my outward strength; and on him I relied for everything in this world.
I am inclined to give forth a testimony to his worth,
as the widow`'s mite to her children, or children`'s children, that when we are gone,
they may see from what kind of stock they have sprung.
For their welfare my very soul is moved within me, and causes me to go bowed down,
imploring that Divine assistance may be their aid through this vale of tears.

[.embedded-content-document.testimony]
--

[.blurb]
=== Jane Pearson`'s Testimony concerning her dear deceased husband, John Pearson, who departed this life the 14th of sixth month, 1774

He was born of believing parents, who gave him a tolerable education; and I believe,
according to the best of their ability, trained him up in the nurture of the Lord.
He was religiously inclined from his youth,
so that in some sense he was a Nazarite from his birth;
giving full proof that he sought a better country than this world;
in which he had various struggles, being more exposed than many others,
as his business was a linen manufacturer;
yet he conducted himself with honor through all his engagements,
and gained a handsome subsistence for his family; and I may say without doubt,
he retained the better part through all.

He was a man of an innocent life and conversation, of a meek disposition,
readier to take harsh treatment than to give it, and would suffer wrong,
rather than resent an injury.
He was temperate even to abstinence.
In the relation of a husband, he was unexceptionable.
When I consider his tenderness towards me and his family, I can scarcely but lament;
yet I believe he is removed to the haven of rest;
for I thought it was demonstrable that the grave
would have no victory at his dissolution.
His illness was tedious, but he was quite resigned,
whether life or death should be his portion; and he frequently said,
he longed to be gone,
and that he scarcely thought it would be possible for him to be so willing to leave us.

A Friend coming in the day before he died, had an opportunity with him,
which was an acceptable time.
The Friend expressed to him that he might yet get a little better.
He answered, "`I had rather go; I have felt the pains of death; oh let me go!`"
It appeared that he was quite reconciled to the grave; and I said,
"`O then, my dear, you must be satisfied your change will be well?`"
He answered, "`Yes, I believe so;`" speaking with becoming humility.
The day before he died, he felt his pulse steadily three times,
in order to know how near his change was;
and inquired of the doctor how long he might continue.
I desired he might not ask that question, and he, lamb-like, did not repeat it.

I am satisfied he had an assurance of acceptance with the Almighty,
which declared itself in the heavenly fortitude and
serenity that accompanied him to his last moments.
His mother, who was an aged person, and under great infirmities,
being brought in to take her leave of him, he in a prophetic manner,
told her he should go first, but she would soon follow after;
and accordingly it proved so, for as he expired,
she began to show symptoms of her dissolution,
and continued but about two hours after him;
so they finished their course nearly together.

Oh! my loss is inexpressible! his kindness, his nearness in a religious sense,
cannot be set forth by me.
I had gone through various and deep provings; many weary years had passed over my head,
while I was under the preparing hand of my God; but his compassion,
his patience towards me, his condescension to my weakness, in my infant state,
cannot be penned.
His memory is blessed;
and his excellent virtues ascend to the Father of spirits and
resemble the prayers and alms-deeds of Cornelius,
had in everlasting remembrance.

I have endeavored not to be swayed by affection, in this summary account,
but have just related what I think the spirit in me bears witness to the truth of;
neither was I easy without doing it.
He departed without any struggle, as one falling into the sweetest of slumbers,
and was decently buried in Friends`' burying-ground, at Graysouthen,
aged forty-nine years.

[.signed-section-signature]
Jane Pearson.

--

The Lord was now about to divest me of my beloveds;
the next year He took my eldest son in a fever, so that I had no son.
He also made it manifest to me,
that it was His requiring I should travel a little in the service of Truth.
I gave up, and my friends favored me with a certificate.
I set off on my journey, with my much honored friend Hannah Harris.
I accompanied her through Lancashire,
and then my dear friend Barbara Drewry met me at Settle.
We visited Yorkshire, except Richmond Monthly Meeting.
Then feeling a strong draft home, I returned and found my family well,
except my dear mother who resided with me.
She was a little on the decline, yet not so as to be much noticed;
but in about two or three weeks, she fell sick and died.
I mention this that Friends may attend to their feelings and drawings,
as to returning home; for had she departed in my absence,
I should have been in danger of letting in the reasoner.
Oh, the kindness of God, who prolonged her life till my return.

I was now left with my father-in-law, who was a valuable man, and my four daughters.
The youngest but one, an amiable young woman of about nineteen, going a little abroad,
lost her health.
She continued in a state of great weakness, for about three years,
and departed this life in 1784, my father-in-law dying a little before her.

[.offset]
+++[+++The compiler of these memoirs, has stated in the introduction,
that the subject of them occasionally wrote a few verses.
On the event just mentioned, she poured forth her maternal feelings, nearly as follows,
without any view to their insertion here;
but perhaps the introduction of them may not be deemed improper.]

=== Lines on my beloved daughter, Hannah Pearson.

[verse]
____
A widow`'d mother while I sit,
In silence and dismay,
I feel a spirit-stirring power,
That prompts the sorrowing lay.

Then from a mother`'s bosom,
Let the mournful numbers flow;
The ear of pity will forgive,
My mingling hope and woe.

There are who hold that life is but
A shadow or a flower;
My soul aspires to higher good,
Than bounds the present hour:

That good, my Hannah sure has reach`'d
And will forever prove:
Her bosom was the abode of peace,
Of innocence and love.

For those whom evil tongues traduced,
She felt compassion rise;
While innocence, the richest gem!
Sat lovely in her eyes.

Strict modesty around her form,
Was like a mantle cast;
Her features beam`'d intelligence,
But--these from earth are past!

Then who can tell the loss of her,
Or number up my tears!
I live: but ah! a sadness hangs
O`'er my declining years.

My dearest consort died again
In Hannah`'s parting breath:
My days are spent in grief, for who
Has known so much of death!

Sweet were your words, my beauteous child,
That you to me express`'d.
When, watching your declining strength,
I hung upon your breast.

And in the anguish of my soul,
To God prefer`'d my prayer.
That, in compassion, yet your life,
He would be pleased to spare.

You meekly answered "`Mother dear!
I`'d rather go than thee,
If such the righteous will of God;
For best that will must be:

Tho`' parted for a little space,
We`'ll hope to meet again.`"
Such resignation gave me strength,
The conflict to sustain.

Can I describe the setting eye?
The faltering tongue restore?
The trembling hand? the shorten`'d breath?--
I cease--for all is over.

Fair as a lily, and as sweet,
My lovely Hannah grew;
But soon she from the garden here,
To Paradise withdrew.

You sister lilies! keep like her,
Your innocence and love,
When gather`'d from the earth, you`'ll then
In beauty rise above.
____

I was now left with three daughters.
The family sits solitary that was full of people;
but the Lord has been exceedingly kind to me.
When I mourned for the loss of my connections, my husband especially,
condescending kindness vouchsafed thus to plead with me; "`What have I done to you?
I have taken your beloveds to a mansion of rest, called them to a better life;
and I will remove, as it pleases Me, the remainder of your family;
and then you will meet, never more to part.`"
At this moment I had a hope, a precious faith,
that the Lord would mercifully preserve me and mine till the conclusion,
in a degree of innocence.

I may acknowledge, I had allowed a strong persuasion to prevail in my mind,
that the Lord in displeasure, had removed my husband from me;
because I had not faithfully discharged myself in the ministry,
or that something was wrong with me;
and I was even so weak as to require a sign from Him,
although He had before fully satisfied me that it was not in displeasure to either of us:
but oh! it was with me a time of great dejection.
What I asked at that time was, that He would cause some of His servants,
with whom I had never corresponded, to write to me, and I would take it as a sign.
He had chastened in His mercy, and now He seemed to be entreated;
for that valuable Friend, Mabel Wigham, addressed me in tender sympathy,
and communicated her feelings that my husband was removed in mercy,
and that I and my children would be preserved.
I note this, that Friends may be faithful in all respects, for it did me much good.

I had now a concern of mind, and I think it had been before me for some years,
to visit the meetings of Friends in the western part of this nation.
Cornwall pressed very close, that had I had wings, I could have flown to it for rest.
I informed some of my friends, who encouraged me and united with me in my prospect.
I then acquainted the Monthly Meeting, and obtained its certificate,
and I had my dear friend, M. Haworth, of Haslingden, for a companion.
We visited most meetings in Lancashire, Cheshire, Shropshire, Worcestershire,
Somersetshire, Devonshire, and Cornwall.

I had a close concern to visit a Friend who had been low for some time,
and mentioned it to some Friends, but way was not made suitable to my diffidence.
When I got as far back as Plymouth, I did not know but I must have returned; for,
if I may be allowed the expression, the furnace was hot,
which made my anguish inexpressible; it made all my bones to shake,
and affected my health for the remainder of the journey, which till then had been good.
Friends had need to be careful how they turn back diffident minds,
who are not like the offspring of Sceva, taking upon them, in their own strength,
to call over unclean spirits.
The Lord wrought mightily in me towards the distressed,
for I had passed through much affliction, and was thereby rendered very susceptible,
readily catching a sense of sorrow wherever I found it.

I believe the Friends were backward of giving encouragement,
wishing to conceal the infirmities that had overtaken
so valuable an instrument as she had been:
and besides all this, many much more worthy had visited her,
with whom indeed I am not fit to be ranked.
But I am what I am, by the grace of God; and as He works wonders by mean low instruments,
He may work through such to others if He please.
I must however own that they gave permission to me, but not to my companion,
and an allowance differs from a hearty concurrence;
yet I have felt judgment for the omission, but believed before I left the place,
that deliverance would come from another source;
and I have lived to know and be thankful for it.
I missed several meetings in my way home, being poorly,
and believing it safe and lawful for me to return.
I found my family well, and had the evidence of peace answering my obedience.

I have now arrived at the fifty-sixth year of my age, and still afflictions abide me.
My second daughter being removed by death, I have but two remaining.
She was an innocent, virtuous young woman,
bore a lingering illness with patience and resignation,
and I believe is gathered in mercy.

In 1791 I moved to Whitehaven to reside, before the death of my youngest daughter;
to whose marriage with a Friend belonging to that meeting, I had consented.
Our going there, was also much the mind of both my daughters.
My daughter who resided with me was desirous of living there,
in order to be helpful to her married sister, whose family was increasing.
Oh, the close exercise I have had in this meeting! truly it has worn me down,
with other trying circumstances which befell me at that place.
Many a bitter cup have I and my poor children drunk of there.
If it has but tended to our refinement, it is well;
for surely our bodies were enfeebled thereby.
I did my best under the heavy trials I met with.
The Lord knows my prayers were almost incessant,
while under the weight of unpleasant things.

My youngest daughter was a religious, pious young woman, and died the year we removed.
She was exceedingly delicate, of a meek disposition, and tender spirited;
and yet she had waded through difficulties, so that in her dying moments she expressed,
that streams of tears had run down her cheeks; and that if she died then,
which she was not afraid to do, she died innocent;
for that she had never done ill to any one.
And she often said encouragingly; "`The Lord knows what is best for us.`"
She had a strong apprehension that she should die;
but from a sweet prospect of good that I had had in our meeting a little before,
in my low wading respecting her, I did believe all would be well;
and from this discovery, I caught a hope that she might recover;
which she remarked during her illness.
"`Mother,`" said she, "`you have been mistaken.`"
I answered: "`My dear, I saw something so comfortable about you,
I believed all would be well;`" she answered: "`All will be well,`" and added,
"`I have often thought of that Friend from Manchester,
who pointed out to us in a family sitting, that some had not long to stay;
but the state he spoke to, seemed too good for me to accept of.
I was willing to put it to another in the company, who at that time was indisposed.`"
She left three fine children in charge to surviving relations.

Though it is my lot often to sit silent at meetings in the place where I now reside;
yet I have precious openings and Divine intimations on my return home from them,
even respecting individuals.
But hardness of heart has crept into the minds of some,
and it may be right to let them alone.

2nd of sixth month, 1793.
I know not for what I am held at this place,
except it be faithfully to suffer with the suffering seed here.
I have renewedly felt a precious union with our dear Lord in His crucified state,
in the hearts of professors.
Oh, the plungings witnessed in our meetings!
There is an active spirit got in, that takes its food upon the surface,
or catches at it flying in the airy regions.
With food of this nature, some seek to feed and to be fed.
I have painfully sat under some recent testimonies, when it seemed clear to me,
sin held its empire: and what was delivered, though sound truths,
yet did not slay the man of sin: but I am alluding to none belonging to our meeting;
there is a precious seed in this place, with which in a great measure, I can unite.

1st of fifth month, 1794.
I have been at meeting this day, which was heavy; I felt clouds gathering thickly,
the sun and moon darkened, the greater and lesser lights withdrawn;
that in my deeply trying, inward labor, I saw no light in the horizon,
and very confidently believed the bitterness of death was around.
I struggled in silence till my gracious Master gave me to see, that where He was,
His servant should be also.
I derived some consolation therefrom;
reposing in a belief that I was of the suffering seed,
though the least member in the body, or the meanest in the Father`'s house.
I think I have had in this meeting, such a diversity of feelings,
that perhaps I have experienced the two extremes of happiness and woe.
At one time in silence, there was a confirming language inwardly spoken;
and though a poor worm, I had hopes it might be applied to myself.
It was: "`My presence shall go with you, and I will give you rest;`"^
footnote:[Exodus 33:14]
under which I was ready to sing the song of Moses, the servant of the Lord,
and the song of the Lamb.
At another time, my mind was so overshadowed with the power of Truth,
that the season was too solemn for any vocal voice to be heard,
the cloud and glory so great, that none could minister.

Sixth month.
I am now returned from Broughton, where I have been nine weeks,
on account of my only surviving daughter`'s weak state of health.
I felt comfortable while there,
and much enlargement of heart towards the few Friends belonging to that place.
Oh, may they be profited!
Truly it was free mercy handed to them,
and not for works of righteousness that they have done,
for I think them deficient in that great duty of attending religious meetings.
How sorrowful it is, when elders and overseers stay at home by their stuff,
while others are wading deeply for the promotion of Truth!

Whitehaven, eighth month, 1794.
This day our Monthly Meeting has been a very favored season to me.
My soul arose above all its troubles, under a precious sense,
that in my sojourning thus far through life,
the Lord has always eyed me for good and has watched my goings;
and though I cannot say I never made false steps, yet He who knows my heart,
knows it to be weakness.
Oh, how weak are we, when divested of His saving help!
Yet He has in mercy fully forgiven all,
and deigned to give me a foretaste of the joys of His kingdom:
a sense that has no feeling of sorrow; no more sighing; no weepings,
but a joy without alloy.
In this state I have been ready to think the days of my mourning are nearly ended,
having a strong "`desire to depart and to be with Christ;`"^
footnote:[Philippians 1:23]
feeling all my soul`'s enemies subdued,
so that I could pray for them that have despitefully used me.
In this heavenly place in Christ Jesus, it is good for us to abide.
This day I was silent; the fulness of glory too great to minister.

22nd, 1794. Have been at meeting.
Oh, the sifting I have, in regard to the ministry I am gifted with!
Though I believe I was rightly called, that I entered at the right time,
and have moved with godly fear in it, not choosing my own way, nor carving for myself,
yet I am so low as to think I have never been of use.
I opened my mouth this day, as I thought, from a small impulse,
or the moving of prophetic instruction, out of my little flour to bake a cake first.
Here is no redundancy now, but a grain of faith that a supply may be afforded,
answering my need.
I ventured my offering in the simplicity, so far as I know; but oh,
the buffeting at my return home was truly bitter!

I am now arrived near the sixtieth year of my age;
and my bodily strength is much impaired: I am grown very weak.
I do not expect it will be long,
before the narrow confines of the silent grave will enclose me.
Happy moment, when I shall be freed from the sight and voice of the oppressor:
for although some might be sensible that I have undergone hard things,
yet none have known the anguish of my heart; it is beyond all description,
but it is known to God.
I have often had to remember holy Job, and to quote him in the exercise of my gift,
in honest labor among the people, and to say,
"`Even today is my complaint bitter, my stroke is heavier than my groaning;`"^
footnote:[Job 23:2]
and so has mine been, even at this late period of my life.
He also declares, he cried out of wrong, but was not heard, yes, cried aloud,
but there was no judgment.

I ventured to conclude this day, as at some former seasons,
that I would preach no more in this place; for the spring of the Gospel is much shut.
I find if I speak, my grief is not assuaged, if I forbear, what am I eased?
For I have tried from meeting to meeting what silence would do for me.
I search myself to find the cause,
that I am not lively in my ministry as in the days of my youth:
for truly I conclude there is no life in me,
so that I now most earnestly wish for the lodging of a wayfaring man in the wilderness,
where I might go from my people and leave them.
I feel weary of these suffering seasons; they are more than my frame can well bear.

Fourth month 8th, 1795.
I was at our week-day meeting, in which I beheld that we are born to trouble,
as the sparks fly upwards; that the human mind at seasons, is like a sponge,
drinking up affliction, till it sinks in deep waters; yes, they flow into the soul.
Oh! the perplexities experienced in this space of time!
Few and evil have been our days, and we have not attained to the years of our progenitors.
In this state,
condescending kindness vouchsafed to lead me to the rock that is higher than I;
and my eyes saw that we fret for things unworthy the notice of a redeemed mind;
and that if I, or my friends with whom I sat,
were but called upon to take leave of everything below the sun,
all these perplexing anxieties would vanish like an atom in the whirlwind,
and be of no weight at all.
We should then only lament that we had not looked above these momentary afflictions,
and fixed our confidence on the invisible Arm, and invincible power of Omnipotence.
But oh! how is the natural part attracted by visible
objects! while that which is born from above,
suffers through our not adhering to the invisible.

In this meeting I desired that I might be favored with an extraordinary visitation,
whereby I might be made willing to give up to any requirings,
having long had an exceedingly great dread upon my spirit,
in regard to praying in public assemblies.
Ah! this broke the creaturely part in me, and laid me in the dust.
I could be willing to breathe mentally during the whole of a meeting:
but when I should have fallen upon my knees, oh, the reasonings I had;
as that the cup of favor was not full enough:
that I had not come so near to His seat as I ought,
or was not sufficiently clothed with the garment of praise;
that fervent desire for my friends, was not arrived at full height;
or that I had not enough of the indwelling of God`'s pure Spirit, to enable me,
in this awful gift of prayer, to keep so close to His precious, directing,
all-saving power, as to be preserved from offering a word in prayer,
of which He was not the author and requirer.

Although this is a pinching dispensation, and I may now appear very like a weakling,
just entered into the service, yet I have at different times been prevailed upon,
to call upon the name of the Lord in public.
But I have had great searching of heart afterward,
lest I should have made the smallest deviation or sally from the precious life,
while so concerned;
that now nature is likely to fail at the appearance and approach of intercession.
May the Lord help me!
Perhaps this little delineation, may be as face answering face in a glass,
to some who are very conscientious in every movement, especially prayer;
and may that always be offered with a right understanding, seasoned with grace.
