== Section 3

[.chapter-synopsis]
* Carlisle Quarterly Meeting, 1797
* Verses written under trial
* Illness in 1800
* Prospect of a religious visit
* Observations, Remarkable vision
* Illness of her only remaining daughter
* Her decease and burial, 1806
* Observations in 1807 and 1808, on entering her seventy-fifth year, and in subsequent parts of 1810
* Extract from Piety Promoted.

20th of eleventh month, 1796.
I have felt a desire this morning to be thoroughly washed, until I be made clean,
so as no fuller on earth could make more white.
Many are made willing to bear the spiritual baptisms,
provided they are assured it is Jesus that is dipping them.
But so uncertain and seemingly casual are the occasions of their plungings,
they believe not that He is the author of their immersion,
or that it is His holy hand that is washing and bathing them for their imperfections.
Sin being mercifully done away, how can these that are dead to sin,
live any longer in it!

Third month 28th, 1797.
I was favored once more to attend our Quarterly Meeting at Carlisle,
very near the place of my nativity, and the meeting I belonged to for many years.
The meeting of ministers and elders was a favored season;
I had the evidence of peace in my little labors;
and indeed all the meetings were more or less owned
with the heart-solacing presence of Zion's King.
It was like taking my leave; and I was helped to be faithful:
so that in my return for many miles, my cup ran over,
and I seemed anointed with the oil of gladness.
Great was my peace; such a full foretaste of heavenly joy,
as I have not before experienced, except when I first opened my mouth in testimony.
There seemed nothing between my soul and its blessed Redeemer.
At that time my joy was so full, that I longed to be dissolved,
feeling nothing but purity and holiness about me; or at least,
I had the sense of full acceptance with the Father, in my endeavors to obey.

At Carlisle, I felt an engagement to supplicate God on behalf of the people:
I felt love for them, and some of the elders and ministers were near my best life.
Indeed I had never found more openness to plead with them,
than in the select opportunity for ministers and elders, and had great peace in so doing.
In the time of supplication, which was at the close of the last meeting,
I thought I found near access to the Almighty; if I had not,
I dared not have called vocally upon His ever blessed and worthy name.
During the awful and solemn season (it was so to me), I supported myself on one knee,
my other having no strength in it, which hindered my continuing so long in intercession,
as might have tended to my solid comfort.
But the Almighty heard the little, who accepts the "`Abba Father.`"
I believe my effort was accepted;
and if I had but bent my knees and called upon His ever worthy name, He being the author,
would in return for this humiliating dedication, have given the answer of peace.
Blessed be the name of the Lord forever.

28th of twelfth month, 1798.
Much proved.

[verse]
____
In age assist me, dearest Lord!
In faith my spirit stay;
And if I've err'd through slavish fear,
Forgive me Lord! I pray.

No other foes assail me now,
Or prey upon my peace,
But false alarms and slavish fears;
Oh cause these fears to cease!

Uplifted hands and downcast eyes,
Bespeak my griefs, O Lord!
To trembling knees and broken sighs,
Your succor now afford.

Desert not Lord, this feeble frame,
You know'st what I can bear,
And when I cry in agony,
Oh! be not slow to hear!

My head is clad with silver hairs;
My limbs their power resign.
Remembering my departed strength.
Let me receive of thine.

Your presence is unsullied joy;
It fills the heavens above.
My earnest cry is, Lord! to feel
A portion of Your love;

My trust in thee was early fixed;
I felt it in my youth;
My age, as then, relies on thee,
Eternal God of Truth!

You have commanded us to ask,
In order to receive;
Admit me to Your holy rest.
When all below I leave.

The mansion You prepare there
Will fully satisfy,
You've raised Your humble handmaid here;
Receive me when I die.

Yet once again, oh! let me come,
Bearing the widow's prayer;
That I and mine, through endless life,
May of Your mercy share.

I have no other claim to make,
Enough for me and mine;
Tho' smallest of the lights in heaven.
If there our lamps may shine.
____

Fourth month, 1800.
I have been confined of late, through bodily indisposition, during the forepart of which,
my sickness was extreme.
It appeared to me that I was making quick advances towards the grave;
although as I apprehended, the first Divine impression was,
that I should not die at that time.
But as I knew a recent instance of a minister of my acquaintance,
and with whom I had travelled, whose dissolution was entirely hid from her,
this made me sometimes rather hesitate.

I had much bodily illness, but not much conflict of mind.
I was preserved still and quiet, which was not my nature; it was God's mercy:
to His praise be it inscribed upon my heart as long as I live.
I was favored with a fixed, steady, comfortable hope, that if I then died,
it would be well with me.
I seek no more evidence, when I shall really surrender life;
for it seemed as if my dear Redeemer's arms enfolded me very safely;
so that the wicked one, by whom I had often been distressed on a sick bed,
touched me not, neither had any power over me.

First-day, 10th of fifth month, 1801.
I was at meeting at Whitehaven, and had a precious opening,
with which I was nearly ready to stand up;
but I am too much like the impotent man at the pool,
waiting for the moving of the waters, and while I am making ready, another steps in.
It was so this day, and though but a few words were spoken,
and they not distinctly heard by me,
yet it left unspeakable anguish and bitterness of spirit, so that the daughter of Judah,
for the remainder of the day, "`was trodden as in a wine press.`"

Ninth month, 1801.
As in me there has been a singular instance of God's mercy and power;
His mercy in forgiving, and power in upholding me,
I can therefore do no less than praise Him here and eternally.
And whoever reads this, let them be humbled in the dust before Him;
for truly He is glorious in holiness, fearful in praises, doing wonders.

The latter part of this year, I have had a time of confinement, through sickness;
and have not been so favored in this season of weakness,
with that soul-sustaining evidence of Divine regard, as at some former times.
It may be that I had too frequent recourse to the redundancy of favor,
then mercifully vouchsafed: not doubting, that if I was similarly tried,
I might be equally supported; and so was in danger of being like Gideon, who,
after his great achievement made an Ephod, and idolizing it,
the same became a snare unto him.

Sixth month 30th, 1802.
I was at our weekday meeting, and was favored with a solemn silence,
resembling that in heaven, where angels and archangels adore in profound silence.
Oh!
I saw into the joys thereof; a place where sorrow cannot come:
none of the inhabitants have any affliction.
I was this day favored to partake of Divine good,
in the greatest degree that perhaps I ever experienced;
the heavenly bread was handed to my soul, in no sparing portion, with, "`Take, eat,
this is My body.`"

Towards the latter end of last year, 1801,
I had an apprehension that I must visit some of the southern counties,
or the southeastern.
It came, I thought, with considerable clearness.
I endeavored to keep as near to good as possible, and rarely, when awake,
was without some sense of the Divine requirings.
The latter end of the fifth month, 1802, seemed the right time for me to move in it.
I did not stagger at my own weak state, for I was really given up;
nor at the extreme weakness of my only surviving child;
so that it appeared like Abraham's trial,
in stretching out his hand to offer his only son.

My poor grandchildren, who indeed were orphans, I wholly resigned,
not daring to let the affectionate part take hold; but gave up my own life and theirs,
and all that I had into the hands of the Almighty; not daring to draw back one jot,
or even to wish that the service had not been required of me.

I dared no more dispute the voice, than Abraham did,
when he was called to go to the land of Moriah; my nature perhaps recoiled,
as his might do, without the hope that he had;
"`My son, the Lord will provide Himself an offering.`"^
footnote:[Genesis 22:8]
Let the unbelievers step forward and question these and other sacred truths;
it matters not; their unbelief will perish with them,
and cease to be propagated when they are no more.

When the time arrived in which I was to prepare for the journey,
the prospect entirely closed, and I was fully released.
I bowed in humility, and accepted my discharge, with this caution,
to eye the great Leader, and not hastily to reenter into my family affairs;
but to be still and wait, without rejoicing at my liberation;
since which time I have continued to feel at liberty.

Fourth month 12th, 1803.
This morning before I rose, I was pondering in my mind, that many in our Society,
are rich and full, as may be seen by their way of living and their clothing;
and that though their garb is plain, yet it is costly;
and various are their suits of apparel.
I then recurred to my own low estate, not regretting that it was so;
for it became a redeemed people to be exemplary in eating, drinking, and apparel:
in which revolvings, my mind was satisfied by this language;
"`I will clothe you with salvation, and crown your end with peace.`"

Could I ask more for myself?
Surely no! and being favored and broken under it, and very near the throne of grace,
I was allowed, in humility, to petition for my daughter,
that she might have a place in the kingdom of heaven,
and accompany my spirit in the mansion seen fit for me to inherit,
when I was unclothed of mortality.
After this, I prayed for my grandchildren.

Twelfth month 23rd, 1804.
First-day, I was at our meeting, in which I had an open time,
much to my own satisfaction: and I hope to that of others.
Indeed, Truth rose into dominion, and the opposite power sunk into insignificance.
Such instances have been rare with me.
In leaving the meeting, a sense of acceptance was given me;
measurably receiving the sentence of well done in my own particular; with a secret hope,
that if I continued to steer my course carefully, eyeing my guide;
and in simplicity and godly sincerity dealing out to the people as immediately given;
pursuing the thread of my testimony in the power, and depending wholly upon the Lord,
He would be mouth and wisdom, tongue and utterance.
Thus Satan for a while, became bruised under foot.

Fourth month 7th, 1805.
I have this day experienced deep baptism of soul.
I thought it would hasten my dissolution.
Oh! merciful Lord, my times are in Your hand; You know what I can bear;
lighten my load I pray You, or add to my strength, for I am tried to the very life;
"`crucified with Christ, nevertheless I live, yet not I, but Christ lives in me.`"^
footnote:[Galatians 2:20]
Oh! grant me patience to bear these suffering seasons;
surely You care that I serve alone.

In the latter end of 1805, or the beginning of 1806, I had a sickness,
in which I was confined for some time; and one night as I lay in bed,
between the hours of nine and ten o'clock, being in a solid, weighty frame of spirit,
breathing towards the Fountain of all good, I beheld with my spiritual eye,
as clearly as ever my outward eye beheld any object, that the Ancient of Days descended;
His dread majesty enveloped as in a cloud;
and being emboldened through His unmerited condescension,
I begged for a place in His glorious kingdom, when unclothed of my mortal robes.
I write in awful fear.
I thought it was granted, and that I was allowed to proceed, if I had any thing further.
I then craved for my only daughter the same favor.
I thought that too was granted.

I then lifted up my eyes and heart, and mentally poured forth my soul, saying: "`Oh!
Lord, the wickedness of man is great;`" my mind being expanded,
and bending in good will towards all; and the answer I received was:
"`My mercy is greater;`" and the vision closed.
But oh! the contented calm it left.

It is now nearly fifteen months since this display of God's mercy occurred;
and till this time, I have not recorded it, lest any should think of me above what I am;
or that from such a discovery of unlimited mercy,
any sinner should presume to go on in their wickedness,
in hopes that God would show them mercy at last.
But at this time, it has been again opened; and after passing many deep plungings,
I am stripped of all glorying, save in the cross;
having no desire but that these lines may preach when I am no more,
and encourage some poor sinner, to lift up his head in hope at what I have penned.

1806+++.+++ I am now grown old,
and it is announced that my declining years are not to be exempt from trials:
they truly increase.
My only daughter is afflicted with a cancer in her breast.
The pain and dreadfulness of the complaint are such,
that we languish without hope of her recovery.
Afflictive is this dispensation indeed; no solace but from a comfortable hope,
that her troubles will end with the termination of her life.

Twelfth month 3rd, 1806.
In our weekday meeting,
I was engaged to set forth the necessity of not only receiving the seed of the kingdom,
but, with all readiness, allowing its growth;
as the work of Truth in the heart of man is described by our Great Master,
to be progressive; first the blade, then the ear, then the full corn in the ear.
I had peace in returning to my habitation, and this language presented to me;
"`Ever since you were born, My love has been to you.`"
This melted me; may I be worthy of such a favor.

Third month 14th, 1807.
On taking a retrospect of the path assigned me through this vale of tears,
and the sketches I have drawn thereof, I have thought it may appear to others,
that I have been more marred than my contemporaries, in my deep early refinings;
and since, in being singularly stripped of my beloved outward connexions;
the tree being wholly peeled.
But let none of Zion's travelers be discouraged thereat; for,
to the praise of my heavenly Father, and of the riches of His grace, be it remembered,
that sufficient strength for the day has been afforded,
or else I never could have stood to this time.
My eldest and last daughter is now released from all her trials, and a gracious God,
who never fails in time of need, visited and upheld my mind in a marvelous manner.

At the time of her interment, while I sat in the meeting beside her coffin,
oh! the unspeakable peace I felt,
with a consoling assurance that all her tears were forever wiped away.
They had flowed like rivers, under deep religious exercise; and at that time,
the condescension of our heavenly Father was such to me, a poor unworthy creature,
that it seemed as if her pure spirit descended and rested upon her remains,
during the opportunity.
Oh! how can I sufficiently adore!

Fifth month 4th, 1807.
Fourth-day, I was at meeting.
Some of our Friends are set off for London.
A solemn time it was to me; for I was much engaged in mental breathings;
the Spirit helping my infirmities inwardly to pray.
A large portion of heavenly bread was handed to me, without much wrestling,
or having it to set before others: and although our souls' enemies may be numerous,
a language livingly opened;
"`The Lord shall fight for you, and you shall hold your peace.`"^
footnote:[Exodus 14:14]
It applied to myself, as I had no commission to divulge it.
Somewhat like the earnest of the Spirit of adoption or holy promise, accompanied my mind,
and closed with,
"`Lord, You are good to us, we will praise You; we will exalt Your name.`"
I had strong consolation in God, only wise.
Omnipotent, Omniscient, and Omnipresent.
Always in His sight, naked and bare before Him, oh! who dare do evil!

Twelfth month 13th, 1807.
My family all gone to meeting; and I through indisposition, left at home;
but I must acknowledge the kindness of a gracious God to me,
who has been near in this time of confinement, allowing me to pour forth my soul, yes,
I have thought sometimes, to lean on His very bosom; and the comforting watch-word is:
"`Fear not, I am first and last.`"^
footnote:[Revelation 1:17]

First month 4th, 1808.
Rich favor extended this morning to me, a poor worm;
and given in these consoling characters; "`My love and care, yes, protecting care,
have ever been towards you; and I never will leave you nor forsake you:
although Satan has, in days past, been permitted to roar and shoot his malignant arrows,
he shall now be still.`"

I craved the renewal of the Divine vision I had been favored with in a former illness;
but Infinite Wisdom saw fit to withhold any thing further of that nature;
I adore and bless His holy name.
Oh! I pray God, with my whole heart, that it may be thus with me in my last moments;
and I humbly trust it will, if I keep my place to the conclusion;
for truly He has been a merciful God to me.
May the members of this meeting, more and more seek after the power,
which has so eminently interposed for the deliverance of my soul!
May not one of them be lost!
For truly great pains have been taken with this part of the vineyard.

Second month 7th, 1808.
For many months, my mind has been preserved in a state of tranquillity,
exclusive of the things in the outward, that were at times afflicting.
There was no evil inclination in myself, nor any temptation thereto;
and a merciful Father not far away from me: that I began to doubt my condition,
lest I should ascribe this serenity, which might become habitual,
to a growth in the Truth and favor with my God, before I had attained it;
so that I almost wished to feel my customary poverty of spirit again, and His chastening;
believing myself far from perfect.
And now He has seen fit to change the benign dispensation,
into one more searching and trying; often withdrawing His favor;
so that I seemed neither "`borne on the side, nor dandled on the knee.`"^
footnote:[Isaiah 66:12]
I will bear it; for oh!
I dread being at ease in Zion,
or trusting to any thing short of what is really substantial,
that feeds and nourishes the soul unto everlasting life.

Fifth month 7th, 1810.
I have now arrived at my seventy-fifth year;
and in perusing again what has long since been written
of the Lord's dealings with me in my childish state,
I feel the renewing of ancient power, which impressed my mind when I penned them;
so that I hope they are not words which will fall to the ground,
for they are faithful and true sayings.
Reader, if when you peruse them, a gentle summons should be heard;
"`The Master is come and calls for you,`"^
footnote:[John 11:28]
rise up quickly, as Mary did; let others suspect what they may, respecting your haste.
These are seasons when we are to salute no one by the way.

There are many publications in the world.
Some of them have a tendency to corrupt the morals of those that read them;
such as these have never come much in my way,
nor dared I have spent my time in reading them.
But there are many deemed more innocent;
and such books as have been introduced into my family,
I have thought it right to view the nature of,
and to consider what tendency they might have
upon minds that seemed to take delight in them;
and I have this to propose to the serious consideration of all, especially the youth,
or even those more advanced in our Society, to whom such books are pleasing;
to such I say;
"`Read the Scriptures and other good books,`" and
observe the tenor of your minds while reading;
and you will feel which of them draws nearer to
God--these publications I have been hinting at,
or those that have been penned by the witnesses of our Savior's life and death.

In the records of His life,
we shall perceive where the Master's footsteps have trodden in deep humility.
Then view His wounded side, and the print of the nails, in viewing which,
living virtue seems to be felt.
Such authors, we must believe, have been with Jesus.
It was reading His sufferings in my early youth, that melted me,
as heretofore acknowledged, and bound me to His pure Spirit.
Oh! that all mankind saw it as I now do! how fearful they would be of
laying out that money for unprofitable publications,
which might be better employed;
neither dare they waste their precious time in reading them.

Eighth month 6th, 1810.
I have been surprised that the older and more infirm I grow,
the more I am enlarged in mind,
and the more illuminated in regard to Scripture sentences.
Oh! how the watchword, when it comes, brightens upon my mind,
and inwardly gives me to expatiate thereupon.
It is the Lord's doing, and marvelous indeed in my eyes.
Lord, what am I, that You continue thus to acknowledge me,
and that You thus expand my heart in old age,
when the keepers of the frail building tremble exceedingly; and I am so humbled thereby,
as to consider myself abject, mean,
and unworthy of a place where the Majesty of heaven resides?
Oh! when this mortal shall put on immortality, and every seed its own body,
mine must surely be as of the lowest order of angels! sown in weakness,
even if it be raised in power.
But cease, my soul, to pry into the secrets of eternity!
The lowest mansion in the Father's house, will far, very far, surpass my services.
Oh, Lord, be near at the winding up of time, is my sincere prayer.

Eleventh month 14th, 1810.
This day we had a very confirming season, in our silent weekday meeting.
I thought I should never more doubt being under the notice of heaven,
the evidence was so strong, and my love seemed perfect Godward;
so that it cast out all fear.
I neither feared death, hell, nor the grave.
The armies of the aliens, for the present, were entirely put to flight.
My faith was strong respecting my own well being,
and even I had faith for those who that day gathered with me.
We seemed indeed come to Zion, the city of the living God,
and gathered in spirit with an innumerable company of angels.

Previous to this precious season, I had had very great openings into Divine things,
pertaining to another life; things so sacred as not to be meddled with;
which brought me to think I should soon be gathered;
and in looking at the ministry I had been gifted with,
and how I had moved under the openings I had been favored with,
although I felt no condemnation, my gift seemed as if it might be taken from me,
yet not in displeasure; I had such siftings in meetings, and was so emptied,
as from vessel to vessel.

I thought the Lord would relieve me from my laborious wadings, which,
I thought to others had been of little service;
and that He would bestow my gift on some other.
I hinted at it in one of our meetings; and although it seemed to me almost unprecedented,
to withhold from fruitfulness; yet my spirit was preserved quiet under it.
And in this week-day meeting I saw, as from the mount,
that such trying seasons as I have often been led into in our meetings, were requisite,
lest I should be exalted through those sublime revelations I have been favored with.
This effected for me what the thorn in the flesh did for Paul:
and I now seemed one of the least, and viewed myself in a truly abject light.

Twelfth month, 1810.
I have transcribed a piece out of Piety Promoted,
+++[+++See the account of Mary Ludgater, part 10, page 139]
thinking perhaps it may be, by me, experienced near my close.

"`It is not always from the most conspicuous on the scene of action,
that we hear the most triumphant expressions of hope and praise,
at the approach of death.
The same baptisms which are the means of qualifying for eminent service,
sometimes induce a fear, a depression, a sense of unworthiness in the instrument,
which makes it slow in believing, that the Lord vouchsafes to regard it,
and that He will finally crown it with eternal blessings;
though it may have often had to hold forth His unfailing loving-kindness,
for the encouragement of others.`"
I am far from looking upon myself as ever conspicuous;
but my unworthiness suggests a fear, that I may be thus tried.

Twelfth month, 1810.
I was confined through indisposition; and my wounded spirit and bleeding heart,
were in great need of inward healing, from the God of all consolation and comfort.
Though one of the unworthiest, I ventured to look towards His holy habitation for help,
and He graciously vouchsafed to heal with these words;
"`no weapon formed against you shall prosper,
and every tongue that rises in judgment against the precious seed,
the Lord will condemn.`"^
footnote:[Isaiah 54:17]
