== Section IV.

Pardshaw Hall Monthly Meeting,
1811--Divers remarks in 1812-13--Her concern respecting her grandson--Several consoling
seasons--Clear evidence respecting her grandson--Account of his decease--Her last remarks,
left in writing--Her close--Testimony of Pardshaw Monthly Meeting respecting her--Conclusion.

Monthly Meeting, Pardshaw Hall, 23rd of seventh month, 1811.--Being at Underwood,
I attended this meeting, and thought it a very favoured time: the glory of the Lord,
as it appeared to me, filled the house; and, sitting upon the mercy seat,
each seemed to have the gracious privilege of pardon.
It brought to my remembrance the apostle Paul,
when he was caught up into the third heaven,
and saw and heard what was not lawful for a finite creature to utter;
neither dared I to utter, on the side of mercy, what I then felt.
I thought if I had continued thus under the immediate sense of God`'s presence,
I should neither have felt hunger nor pain; but it was not a state to be continued in;
for upon my return, the gracious presence was withdrawn.
I do not say a messenger of Satan was sent to buffet;
but I was plunged into heart-rending doubts, respecting my own salvation;
thoroughly preventing my being exalted above measure, for the abundant revelation,
vouchsafed to me at that precious season.

I did not see that I had missed in my communications to the Friends gathered;
I had not kindled a fire and warmed myself with the sparks thereof,
that I had thus to lie down in sorrow.
How awful would be such another season of rising in my spirit,
out of the reach of sorrow, in which there was no partition wall between God and my soul,
lest such another fiery baptism should succeed!
Oh! Lord, I beseech thee, keep me in thy patience;
and let thy refining power leave nothing that is wrong in me, unsubdued.
Thou, Lord! knowest what I have gone through in my youth; and all along,
thy hand has been heavy upon me.
Thou, Lord! has often given me to see that thou imputest no iniquity to me,
but hast given me a sense that I had full acceptance with thee.
"`Why art thou cast down, O my soul! and why art thou disquieted within me?
Hope thou in God, for I shall yet praise Him!`"

In penning these remarks, I find good to arise, which rather binds up my broken heart;
for although I have heavy trials in the outward,
they have had no share in my present plunging.
It was because my beloved had withdrawn himself, and was gone.
A dispensation of this nature would not have dismayed me so much,
provided I had not been so long in the ministry.
The Great Master, I thought, had fully tried me as to exaltation,
and proved that I did not dare to say, "`The Lord saith,`" when he had not spoken;
so that I really hoped I had been established upon the immovable Rock;
but I find they that think they stand, should take heed lest they fall.
Neither are we to recur to those sublime discoveries which the Divine light has manifested;
but, after great favour in vision,
to suffer all to return to the fountain whence it sprang.
Ah! then, how emptied and stripped are we; for vessels used, must be washed.
How unsafe for us to feed upon any good we have been enabled to do!
We experimentally find it to be a truth,
that it is not for works of righteousness which we have done,
but of his mercy we are saved; and that it is by the washing of regeneration,
and the renewing of the holy Ghost; for which I pray.

First month 29th, 1812.--Fourth-day--A precious meeting to me;
indeed I thought the solemnity general.
Oh! the pure silence that I felt,
as if Immanuel stretched forth his wings and covered us:
and that sublime and exalted vision of the prophet
was brought clearly to the view of my mind,
when he "`beheld the Lord sitting upon his throne, high and lifted up,
and his train filled the temple.
Above it stood the seraphims, each had six wings; with twain they covered their face,
with twain they covered their feet, and with twain they did fly: and one said.
Holy, holy, holy, Lord God Almighty; the whole earth is full of thy glory.
And the posts of the door moved at the voice of Him that spoke,
and the house was filled with smoke.`"

I inquired whether I was to divulge it or not; and the answer I received was;
that "`It was favour and food for myself, and that if I gave to others my own portion,
I should soon become meagre and thin.`"
I return thanks, and gratefully acknowledge the favour vouchsafed,
and now conclude to keep close hold of the confirming evidence I then had;
but fear at times assails me, lest I should lose it again and doubt.

Fourth month 5th, 1812.--After a time of illness this morning,
it was mercifully handed to me, as Divine consolation;
"`Thou art in the hollow of my hand;`" and again; "`The Lord is my shepherd,
I shall not lack.`"
Oh, Lord, what an unutterable favour is this, when the weakness of my body is, at times,
as much as nature can bear.
I have passed thus far through the wilderness of this world, in as great jeopardy,
as closely exercised, and as nearly fainting under my trials,
as perhaps ever any poor mortal did.
What an unspeakable favour, when verging to the confines of the narrow and silent grave,
that so unworthy a creature should thus be owned!
Oh! gracious Father! continue thy preserving, protecting care of me,
to the last moments of my life; and I will laud and praise thy name while here,
and eternally.
Amen.

Sixth month, 1812.--Recovering from a recent illness,
I found an inclination to inspect my papers, written under a religious sense;
and on reviewing that extraordinary vision, a fear impressed my mind,
lest any hereafter should think I had exceeded the bounds of a finite creature;
on which it occurred to me, let them call to mind my deep exercises, hard servitude,
and bitter bondage in the iron furnace, in a land of thick darkness, which might be felt.
I was so marred that I became a wonder to my contemporaries.
Now after this,
if a gracious God saw meet to bow the heavens and
come down to touch my heart that it might melt,
He being Omniscient; who, after such great favour,
would lightly esteem the Rock of their salvation!
Although He is the High and holy One who dwelleth in the light, and inhabiteth eternity,
yet we are assured that he condescends to revive the spirits of his poor, contrite,
humble servants, who tremble at his word.

Our blessed Lord and Saviour Jesus Christ,
who is our Intercessor and Mediator between God and man,
when questioned how he would manifest himself to his chosen ones, and not unto the world,
sealed the promise thus; "`If a man love me, he will keep my words,
and my Father will love him, and we will come unto him, and make our abode with him.`"
This is not like the wayfaring man, that turneth aside to tarry for a night, and is gone;
but Christ takes his abode with them, a blessed guest, a teacher at home or within,
that cannot be removed into a corner.

These openings in my mind, confirm a Divine intercourse; and now I leave it;
and if it be thought right wholly to suppress it, or all I have written,
the will of Friends be done in the Truth; for oh!
I dread presumption; knowing the high tree must be laid low, and the low exalted;
the green tree dried up, and the dry made to flourish.

Third month 14th, 1813.--A deep acknowledgment of the mercy of God.
As I lay in bed this morning, under piercing anguish of mind,
on account of my grand-son`'s departure from the Truth; my spirit,
though in the deepest affliction, was permitted to ascend,
I thought even to the Almighty`'s throne;
and I there poured forth my soul on my own and his account;
and condescending kindness vouchsafed, in abundant mercy,
to unveil his benign countenance and let me know,
that the assurances he had given me of his favour, I ought not to dispute;
that if after all the evidences he had given me of his protecting care,
I should cast away my confidence in Him, I should be worse than an infidel;
and then a little hope was revived,
that the poor erring youth would yet be visited in mercy.

This view, if only tending to bind up my broken heart, or to heal my wounded spirit,
I accepted in thankfulness from my God.
Oh! gracious Father, in thy wonted kindness, keep this little flock,
amongst whom I have often laboured, the members of this meeting, when I am no more.
May they never become a desolation, a breeding of nettles;
but continue to come up in the nobility of Truth.
Dear Friends! nothing will do but keeping near to God; dwelling as in his presence.
Do nothing in his sight, that you would be afraid any mortal should see:
keep a pure heart and clean hands, and the end will be peace.
And this love I feel for the Monthly Meeting--the members thereof are dear to me.

Sixth month 2nd, 1813.--Returning from our week-day meeting,
in which I had been faithful according to the vision and sense given me,
this intimation revived; "`The Lord noticeth thy shaking head and trembling limbs,
and in his own time, will set thee at liberty;`" a blessed hope springing up therefrom,
that though sown in weakness, I should be raised in power.
Oh! blessed be his holy name! for he feeds the hungry with good things,
but the rich and full he sends empty away.

Our Monthly Meeting at Whitehaven, in the eighth month, 1813, was to me a solacing season.
Nothing heard but the voice of thanksgiving and praise.
The grand adversary totally overpowered; not one cloud to eclipse the glory of the day,
or dim the beauty of Zion.

Tenth month 21st, 1813.--I have had this day, at the week-day meeting at Whitehaven,
the most undoubted evidence of the overshadowing of Divine love and mercy,
that I remember to have experienced;
truly the wing of the Almighty might be said to be over us.
His reconciliation was offered; and on the side of mercy,
I saw more than I have freedom to write or speak.
Oh, my dear friends! belonging to this meeting, especially those at meeting that day;
let us prize the Lord`'s goodness to our souls.
My love was such to you,
that it appeared almost insupportable that even one
of you should come short of the heavenly rest,
which I beheld was intended for us: far,
very far beyond the conception of any finite creature.

Tenth month 31st,
1813.--Oh! the consoling visions I have experienced during my late confinement.
A tribute of thanksgiving and praise is richly due to my blessed Lord and Master,
Jesus Christ, for the sense he has been pleased to favour me with,
that he hath heard my prayers for my poor grandson; for a little before his death,
the spirit of intercession was poured forth upon me,
and my prayers were strong on his account.

Although I am exceedingly shaken, and my hand very unsteady,
yet if it is right for me to leave to posterity,
the memorable condescension of the Almighty to me, a poor worm,
I shall be able to make it legible.
Upon the 13th of twelfth month, 1813, sitting in the evening by my fire-side,
with company about me engaged in conversing, I felt a strong attraction heavenward,
which I was glad to feel:
and a gracious God seemed pleased to bow his heavens and come down,
directing me to dismiss every doubt respecting my own exit;
for that he would take me in his mercy, and support me through what might befall me;
and my charge was, never more to doubt of my eternal rest.
Also respecting my grandson, I was charged to doubt no more;
for that repentance had been granted even to him at a late hour.^
footnote:[This poor young man was confined to a sick
room in the military hospital at Chelsea,
with many others in the same apartment, which he very much regretted;
because he could not attain to that quiet state of mind which he much wished for.
He was brought to a sense of his mis-steppings,
and expressed the distress he felt for the uneasiness he had occasioned his grandmother,
fearing he should shorten her days; and was very anxious to read his Bible.
He uttered some striking expressions near his close, which are not clearly remembered;
but the day and hour of his death accorded with the consolatory
impressions which his grandmother had respecting him.]
The spirit of intercession was poured forth upon me with such energy,
as seemed to rend the very heavens.--O my soul! never forget that season,
nor ever cease to extol a merciful God, in pardoning transgressors: in this instance,
mercy has covered the judgment seat to a hair`'s breadth.

The Almighty`'s presence was so full and confirming,
that I found it as much as my frail tabernacle could bear and live.
I then experienced that no flesh could see him in his majesty and live.
Although once before I had been in a somewhat similar situation,
yet I had not the sense given me at that time, that if Divine favour increased,
my body could not retain the spirit.
I now desist from pressing after more being exhibited,
feeling overcome with the present extension.
Oh, gracious God!

First month 16th, 1814.--This day after Friends were gone to meeting,
I was very low in mind; when the words of the prophet came very lively,
that he would make the parched ground as a pool;
and after sitting in this disconsolate manner, I was comforted with; "`I am near thee,
though thou knowest it not.`"

Eighth month 4th,
1814.--Oh! the mercy of a gracious God to me in my old age and great bodily infirmity,
who has given me to experience this morning that the just live by faith.
Were it not for this precious faith, I should conclude myself just going,
almost every moment; oh, blessed is thy holy name forever!

Ninth month 19th, 1814.--This morning I again had the most strengthening,
consoling evidence of Divine favour, that my poor frame could bear;
letting me know that as my strength decreased, his watchful care over me increased;
and although he had seen meet nearly to deprive me of my outward hearing,
he had increased the inward so surprisingly,
that I often seem to fall down before him in astonishment;
my mind being so expanded and enlarged, that as naturals abate, spirituals increase;
and my dear Redeemer allows me at seasons, to repose as upon his bosom.

[.asterism]
'''

After this, the subject of this memoir wrote no more for public inspection;
yet for many months, though in great debility, and in bodily pain,
she continued to converse with her friends;
most frequently respecting the goodness of the Almighty, and her latter end;
on which occasion she evinced humble resignation and Christian hope.
It appeared to those who attended her, that the last effort of her pious life was prayer;
but the words could not be gathered.
She quietly departed about three o`'clock, the 20th of second month, 1816,
aged eighty-one.
The testimony of the Monthly Meeting to which she belonged,
may properly conclude these sketches.

[.asterism]
'''
